// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const keepListing = `-- name: KeepListing :execrows

INSERT INTO discovery.branch_listings (
    branch_id, business_id, version, listed, name_ar, name_en, city_code, district, address,
    latitude, longitude, phone, timezone, updated_at, search_text
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
ON CONFLICT (branch_id) DO UPDATE SET
    business_id = excluded.business_id,
    version     = excluded.version,
    listed      = excluded.listed,
    name_ar     = excluded.name_ar,
    name_en     = excluded.name_en,
    city_code   = excluded.city_code,
    district    = excluded.district,
    address     = excluded.address,
    latitude    = excluded.latitude,
    longitude   = excluded.longitude,
    phone       = excluded.phone,
    timezone    = excluded.timezone,
    updated_at  = excluded.updated_at,
    search_text = excluded.search_text
WHERE discovery.branch_listings.version < excluded.version
`

type KeepListingParams struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	SearchText string
}

// discovery's queries. They touch only the discovery schema.
// Saves discovery's copy of a branch, unless the copy already holds this
// version or a newer one: events can arrive twice and out of order.
func (q *Queries) KeepListing(ctx context.Context, arg KeepListingParams) (int64, error) {
	result, err := q.db.Exec(ctx, keepListing,
		arg.BranchID,
		arg.BusinessID,
		arg.Version,
		arg.Listed,
		arg.NameAr,
		arg.NameEn,
		arg.CityCode,
		arg.District,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Timezone,
		arg.UpdatedAt,
		arg.SearchText,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listingsInCity = `-- name: ListingsInCity :many
SELECT branch_id, business_id, version, listed, name_ar, name_en, city_code, district, address,
       latitude, longitude, phone, timezone, updated_at
FROM discovery.branch_listings
WHERE listed AND city_code = $1
  AND ($2::text IS NULL
       OR (name_ar, branch_id) > ($2::text, $3::uuid))
ORDER BY name_ar, branch_id
LIMIT $4
`

type ListingsInCityParams struct {
	CityCode  string
	AfterName *string
	AfterID   *uuid.UUID
	PageSize  int32
}

type ListingsInCityRow struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
}

// A page of a city's listed branches, by Arabic name then ID, after the
// last one of the previous page (none for the first page).
func (q *Queries) ListingsInCity(ctx context.Context, arg ListingsInCityParams) ([]ListingsInCityRow, error) {
	rows, err := q.db.Query(ctx, listingsInCity,
		arg.CityCode,
		arg.AfterName,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingsInCityRow{}
	for rows.Next() {
		var i ListingsInCityRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BusinessID,
			&i.Version,
			&i.Listed,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingsMatching = `-- name: ListingsMatching :many
SELECT branch_id, business_id, version, listed, name_ar, name_en, city_code, district, address,
       latitude, longitude, phone, timezone, updated_at,
       word_similarity($1::text, search_text)::float8 AS sort_key
FROM discovery.branch_listings
WHERE listed
  AND (search_text LIKE '%' || $2::text || '%' OR $1::text <% search_text)
  AND ($3::text IS NULL OR city_code = $3::text)
  AND ($4::float8 IS NULL
       OR word_similarity($1::text, search_text)::float8 < $4::float8
       OR (word_similarity($1::text, search_text)::float8 = $4::float8
           AND branch_id > $5::uuid))
ORDER BY word_similarity($1::text, search_text)::float8 DESC, branch_id
LIMIT $6
`

type ListingsMatchingParams struct {
	Text       string
	TextLike   string
	CityCode   *string
	AfterScore *float64
	AfterID    *uuid.UUID
	PageSize   int32
}

type ListingsMatchingRow struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	SortKey    float64
}

// A page of the listed branches whose names match a search (normalised),
// best match first, then by ID, after the last one of the previous page
// (none for the first page); optionally only one city's. A name matches if
// it contains the search, or a part of it is close to the search
// (word_similarity at least pg_trgm.word_similarity_threshold, which the
// caller sets). The trigram index finds both. sort_key is the match, 0–1.
func (q *Queries) ListingsMatching(ctx context.Context, arg ListingsMatchingParams) ([]ListingsMatchingRow, error) {
	rows, err := q.db.Query(ctx, listingsMatching,
		arg.Text,
		arg.TextLike,
		arg.CityCode,
		arg.AfterScore,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingsMatchingRow{}
	for rows.Next() {
		var i ListingsMatchingRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BusinessID,
			&i.Version,
			&i.Listed,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.UpdatedAt,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingsNear = `-- name: ListingsNear :many
SELECT branch_id, business_id, version, listed, name_ar, name_en, city_code, district, address,
       latitude, longitude, phone, timezone, updated_at,
       (location <-> ST_MakePoint($1::float8, $2::float8)::geography)::float8 AS sort_key
FROM discovery.branch_listings
WHERE listed
  AND ST_DWithin(location, ST_MakePoint($1::float8, $2::float8)::geography, $3::float8, false)
  AND ($4::text IS NULL OR city_code = $4::text)
  AND ($5::text IS NULL
       OR search_text LIKE '%' || $6::text || '%'
       OR $5::text <% search_text)
  AND ($7::float8 IS NULL
       OR (location <-> ST_MakePoint($1::float8, $2::float8)::geography, branch_id)
          > ($7::float8, $8::uuid))
ORDER BY location <-> ST_MakePoint($1::float8, $2::float8)::geography, branch_id
LIMIT $9
`

type ListingsNearParams struct {
	Lng           float64
	Lat           float64
	RadiusM       float64
	CityCode      *string
	Text          *string
	TextLike      *string
	AfterDistance *float64
	AfterID       *uuid.UUID
	PageSize      int32
}

type ListingsNearRow struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	SortKey    float64
}

// A page of the listed branches within radius_m metres of a point, nearest
// first, then by ID, after the last one of the previous page (none for the
// first page); optionally only one city's. Distances are on a sphere: <->
// and ST_DWithin(…, false) agree, so the radius, the order and the cursor
// all use the same number. The GiST index finds the candidates. sort_key
// is the distance in metres (the same name as ListingsMatching's, so the
// two queries share a row type).
func (q *Queries) ListingsNear(ctx context.Context, arg ListingsNearParams) ([]ListingsNearRow, error) {
	rows, err := q.db.Query(ctx, listingsNear,
		arg.Lng,
		arg.Lat,
		arg.RadiusM,
		arg.CityCode,
		arg.Text,
		arg.TextLike,
		arg.AfterDistance,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingsNearRow{}
	for rows.Next() {
		var i ListingsNearRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BusinessID,
			&i.Version,
			&i.Listed,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.UpdatedAt,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
