// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const keepHours = `-- name: KeepHours :execrows
INSERT INTO discovery.branch_hours (branch_id, business_id, version, open, updated_at)
VALUES ($1, $2, $3, ($4::text)::int4multirange, $5)
ON CONFLICT (branch_id) DO UPDATE SET
    business_id = excluded.business_id,
    version     = excluded.version,
    open        = excluded.open,
    updated_at  = excluded.updated_at
WHERE discovery.branch_hours.version < excluded.version
`

type KeepHoursParams struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Open       string
	UpdatedAt  time.Time
}

// Saves discovery's copy of a branch's opening hours, unless the copy
// already holds this version or a newer one. open is the week as text,
// e.g. '{[540,1260),[1980,2700)}'.
func (q *Queries) KeepHours(ctx context.Context, arg KeepHoursParams) (int64, error) {
	result, err := q.db.Exec(ctx, keepHours,
		arg.BranchID,
		arg.BusinessID,
		arg.Version,
		arg.Open,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const keepListing = `-- name: KeepListing :execrows

INSERT INTO discovery.branch_listings (
    branch_id, business_id, version, listed, name_ar, name_en, city_code, district, address,
    latitude, longitude, phone, timezone, updated_at, search_text
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
ON CONFLICT (branch_id) DO UPDATE SET
    business_id = excluded.business_id,
    version     = excluded.version,
    listed      = excluded.listed,
    name_ar     = excluded.name_ar,
    name_en     = excluded.name_en,
    city_code   = excluded.city_code,
    district    = excluded.district,
    address     = excluded.address,
    latitude    = excluded.latitude,
    longitude   = excluded.longitude,
    phone       = excluded.phone,
    timezone    = excluded.timezone,
    updated_at  = excluded.updated_at,
    search_text = excluded.search_text
WHERE discovery.branch_listings.version < excluded.version
`

type KeepListingParams struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	SearchText string
}

// discovery's queries. They touch only the discovery schema.
// Saves discovery's copy of a branch, unless the copy already holds this
// version or a newer one: events can arrive twice and out of order.
func (q *Queries) KeepListing(ctx context.Context, arg KeepListingParams) (int64, error) {
	result, err := q.db.Exec(ctx, keepListing,
		arg.BranchID,
		arg.BusinessID,
		arg.Version,
		arg.Listed,
		arg.NameAr,
		arg.NameEn,
		arg.CityCode,
		arg.District,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Timezone,
		arg.UpdatedAt,
		arg.SearchText,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const keepService = `-- name: KeepService :execrows
INSERT INTO discovery.branch_services (
    service_id, branch_id, business_id, version, offered, category_code, price_from, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (service_id) DO UPDATE SET
    branch_id     = excluded.branch_id,
    business_id   = excluded.business_id,
    version       = excluded.version,
    offered       = excluded.offered,
    category_code = excluded.category_code,
    price_from    = excluded.price_from,
    updated_at    = excluded.updated_at
WHERE discovery.branch_services.version < excluded.version
`

type KeepServiceParams struct {
	ServiceID    uuid.UUID
	BranchID     uuid.UUID
	BusinessID   uuid.UUID
	Version      int32
	Offered      bool
	CategoryCode string
	PriceFrom    int64
	UpdatedAt    time.Time
}

// Saves discovery's copy of a service, unless the copy already holds this
// version or a newer one: events can arrive twice and out of order.
func (q *Queries) KeepService(ctx context.Context, arg KeepServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, keepService,
		arg.ServiceID,
		arg.BranchID,
		arg.BusinessID,
		arg.Version,
		arg.Offered,
		arg.CategoryCode,
		arg.PriceFrom,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listingsInCity = `-- name: ListingsInCity :many
SELECT l.branch_id, l.business_id, l.version, listed, name_ar, name_en, city_code, district, address,
       latitude, longitude, phone, timezone, l.updated_at,
       (SELECT min(s.price_from) FROM discovery.branch_services s
        WHERE s.branch_id = l.branch_id AND s.offered
          AND ($1::text IS NULL OR s.category_code = $1::text))::bigint AS price_from,
       coalesce(discovery.open_at(h.open, $2::timestamptz, l.timezone), false)::bool AS open_now
FROM discovery.branch_listings l
LEFT JOIN discovery.branch_hours h ON h.branch_id = l.branch_id
WHERE listed AND city_code = $3
  AND (NOT $4::bool OR discovery.open_at(h.open, $2::timestamptz, l.timezone))
  AND EXISTS (SELECT FROM discovery.branch_services s
              WHERE s.branch_id = l.branch_id AND s.offered
                AND ($1::text IS NULL OR s.category_code = $1::text))
  AND ($5::text IS NULL
       OR (name_ar, l.branch_id) > ($5::text, $6::uuid))
ORDER BY name_ar, l.branch_id
LIMIT $7
`

type ListingsInCityParams struct {
	Category  *string
	At        time.Time
	CityCode  string
	OpenOnly  bool
	AfterName *string
	AfterID   *uuid.UUID
	PageSize  int32
}

type ListingsInCityRow struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	PriceFrom  int64
	OpenNow    bool
}

// A page of a city's listed branches, by Arabic name then ID, after the
// last one of the previous page (none for the first page). Like every
// search, only branches offering a service (in category, if given), each
// with the least one costs (price_from) and whether it is open at the
// instant at, in its own time zone (open_now); open_only keeps only those.
func (q *Queries) ListingsInCity(ctx context.Context, arg ListingsInCityParams) ([]ListingsInCityRow, error) {
	rows, err := q.db.Query(ctx, listingsInCity,
		arg.Category,
		arg.At,
		arg.CityCode,
		arg.OpenOnly,
		arg.AfterName,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingsInCityRow{}
	for rows.Next() {
		var i ListingsInCityRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BusinessID,
			&i.Version,
			&i.Listed,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.UpdatedAt,
			&i.PriceFrom,
			&i.OpenNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingsMatching = `-- name: ListingsMatching :many
SELECT l.branch_id, l.business_id, l.version, listed, name_ar, name_en, city_code, district, address,
       latitude, longitude, phone, timezone, l.updated_at,
       (SELECT min(s.price_from) FROM discovery.branch_services s
        WHERE s.branch_id = l.branch_id AND s.offered
          AND ($1::text IS NULL OR s.category_code = $1::text))::bigint AS price_from,
       coalesce(discovery.open_at(h.open, $2::timestamptz, l.timezone), false)::bool AS open_now,
       word_similarity($3::text, search_text)::float8 AS sort_key
FROM discovery.branch_listings l
LEFT JOIN discovery.branch_hours h ON h.branch_id = l.branch_id
WHERE listed
  AND (search_text LIKE '%' || $4::text || '%' OR $3::text <% search_text)
  AND (NOT $5::bool OR discovery.open_at(h.open, $2::timestamptz, l.timezone))
  AND EXISTS (SELECT FROM discovery.branch_services s
              WHERE s.branch_id = l.branch_id AND s.offered
                AND ($1::text IS NULL OR s.category_code = $1::text))
  AND ($6::text IS NULL OR city_code = $6::text)
  AND ($7::float8 IS NULL
       OR word_similarity($3::text, search_text)::float8 < $7::float8
       OR (word_similarity($3::text, search_text)::float8 = $7::float8
           AND l.branch_id > $8::uuid))
ORDER BY word_similarity($3::text, search_text)::float8 DESC, l.branch_id
LIMIT $9
`

type ListingsMatchingParams struct {
	Category   *string
	At         time.Time
	Text       string
	TextLike   string
	OpenOnly   bool
	CityCode   *string
	AfterScore *float64
	AfterID    *uuid.UUID
	PageSize   int32
}

type ListingsMatchingRow struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	PriceFrom  int64
	OpenNow    bool
	SortKey    float64
}

// A page of the listed branches whose names match a search (normalised),
// best match first, then by ID, after the last one of the previous page
// (none for the first page); optionally only one city's. A name matches if
// it contains the search, or a part of it is close to the search
// (word_similarity at least pg_trgm.word_similarity_threshold, which the
// caller sets). The trigram index finds both. sort_key is the match, 0–1.
// Offering a service, price_from and open_now as in ListingsInCity.
func (q *Queries) ListingsMatching(ctx context.Context, arg ListingsMatchingParams) ([]ListingsMatchingRow, error) {
	rows, err := q.db.Query(ctx, listingsMatching,
		arg.Category,
		arg.At,
		arg.Text,
		arg.TextLike,
		arg.OpenOnly,
		arg.CityCode,
		arg.AfterScore,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingsMatchingRow{}
	for rows.Next() {
		var i ListingsMatchingRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BusinessID,
			&i.Version,
			&i.Listed,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.UpdatedAt,
			&i.PriceFrom,
			&i.OpenNow,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listingsNear = `-- name: ListingsNear :many
SELECT l.branch_id, l.business_id, l.version, listed, name_ar, name_en, city_code, district, address,
       latitude, longitude, phone, timezone, l.updated_at,
       (SELECT min(s.price_from) FROM discovery.branch_services s
        WHERE s.branch_id = l.branch_id AND s.offered
          AND ($1::text IS NULL OR s.category_code = $1::text))::bigint AS price_from,
       coalesce(discovery.open_at(h.open, $2::timestamptz, l.timezone), false)::bool AS open_now,
       (location <-> ST_MakePoint($3::float8, $4::float8)::geography)::float8 AS sort_key
FROM discovery.branch_listings l
LEFT JOIN discovery.branch_hours h ON h.branch_id = l.branch_id
WHERE listed
  AND ST_DWithin(location, ST_MakePoint($3::float8, $4::float8)::geography, $5::float8, false)
  AND (NOT $6::bool OR discovery.open_at(h.open, $2::timestamptz, l.timezone))
  AND EXISTS (SELECT FROM discovery.branch_services s
              WHERE s.branch_id = l.branch_id AND s.offered
                AND ($1::text IS NULL OR s.category_code = $1::text))
  AND ($7::text IS NULL OR city_code = $7::text)
  AND ($8::text IS NULL
       OR search_text LIKE '%' || $9::text || '%'
       OR $8::text <% search_text)
  AND ($10::float8 IS NULL
       OR (location <-> ST_MakePoint($3::float8, $4::float8)::geography, l.branch_id)
          > ($10::float8, $11::uuid))
ORDER BY location <-> ST_MakePoint($3::float8, $4::float8)::geography, l.branch_id
LIMIT $12
`

type ListingsNearParams struct {
	Category      *string
	At            time.Time
	Lng           float64
	Lat           float64
	RadiusM       float64
	OpenOnly      bool
	CityCode      *string
	Text          *string
	TextLike      *string
	AfterDistance *float64
	AfterID       *uuid.UUID
	PageSize      int32
}

type ListingsNearRow struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	PriceFrom  int64
	OpenNow    bool
	SortKey    float64
}

// A page of the listed branches within radius_m metres of a point, nearest
// first, then by ID, after the last one of the previous page (none for the
// first page); optionally only one city's. Distances are on a sphere: <->
// and ST_DWithin(…, false) agree, so the radius, the order and the cursor
// all use the same number. The GiST index finds the candidates. sort_key
// is the distance in metres (the same name as ListingsMatching's, so the
// two queries share a row type). Offering a service, price_from and
// open_now as in ListingsInCity.
func (q *Queries) ListingsNear(ctx context.Context, arg ListingsNearParams) ([]ListingsNearRow, error) {
	rows, err := q.db.Query(ctx, listingsNear,
		arg.Category,
		arg.At,
		arg.Lng,
		arg.Lat,
		arg.RadiusM,
		arg.OpenOnly,
		arg.CityCode,
		arg.Text,
		arg.TextLike,
		arg.AfterDistance,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingsNearRow{}
	for rows.Next() {
		var i ListingsNearRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BusinessID,
			&i.Version,
			&i.Listed,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.UpdatedAt,
			&i.PriceFrom,
			&i.OpenNow,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
