// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const keepListing = `-- name: KeepListing :execrows

INSERT INTO discovery.branch_listings (
    branch_id, business_id, version, listed, name_ar, name_en, city_code, district, address,
    latitude, longitude, phone, timezone, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
ON CONFLICT (branch_id) DO UPDATE SET
    business_id = excluded.business_id,
    version     = excluded.version,
    listed      = excluded.listed,
    name_ar     = excluded.name_ar,
    name_en     = excluded.name_en,
    city_code   = excluded.city_code,
    district    = excluded.district,
    address     = excluded.address,
    latitude    = excluded.latitude,
    longitude   = excluded.longitude,
    phone       = excluded.phone,
    timezone    = excluded.timezone,
    updated_at  = excluded.updated_at
WHERE discovery.branch_listings.version < excluded.version
`

type KeepListingParams struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
}

// discovery's queries. They touch only the discovery schema.
// Saves discovery's copy of a branch, unless the copy already holds this
// version or a newer one: events can arrive twice and out of order.
func (q *Queries) KeepListing(ctx context.Context, arg KeepListingParams) (int64, error) {
	result, err := q.db.Exec(ctx, keepListing,
		arg.BranchID,
		arg.BusinessID,
		arg.Version,
		arg.Listed,
		arg.NameAr,
		arg.NameEn,
		arg.CityCode,
		arg.District,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Timezone,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listingsInCity = `-- name: ListingsInCity :many
SELECT branch_id, business_id, version, listed, name_ar, name_en, city_code, district, address,
       latitude, longitude, phone, timezone, updated_at
FROM discovery.branch_listings
WHERE listed AND city_code = $1
  AND ($2::text IS NULL
       OR (name_ar, branch_id) > ($2::text, $3::uuid))
ORDER BY name_ar, branch_id
LIMIT $4
`

type ListingsInCityParams struct {
	CityCode  string
	AfterName *string
	AfterID   *uuid.UUID
	PageSize  int32
}

// A page of a city's listed branches, by Arabic name then ID, after the
// last one of the previous page (none for the first page).
func (q *Queries) ListingsInCity(ctx context.Context, arg ListingsInCityParams) ([]DiscoveryBranchListing, error) {
	rows, err := q.db.Query(ctx, listingsInCity,
		arg.CityCode,
		arg.AfterName,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoveryBranchListing{}
	for rows.Next() {
		var i DiscoveryBranchListing
		if err := rows.Scan(
			&i.BranchID,
			&i.BusinessID,
			&i.Version,
			&i.Listed,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
