// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BusinessStatus.
const (
	Active        BusinessStatus = "active"
	Draft         BusinessStatus = "draft"
	PendingReview BusinessStatus = "pending_review"
	Rejected      BusinessStatus = "rejected"
	Suspended     BusinessStatus = "suspended"
)

// Valid indicates whether the value is a known member of the BusinessStatus enum.
func (e BusinessStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Draft:
		return true
	case PendingReview:
		return true
	case Rejected:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for StaffRole.
const (
	Barber  StaffRole = "barber"
	Manager StaffRole = "manager"
	Owner   StaffRole = "owner"
)

// Valid indicates whether the value is a known member of the StaffRole enum.
func (e StaffRole) Valid() bool {
	switch e {
	case Barber:
		return true
	case Manager:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserLocale.
const (
	Ar UserLocale = "ar"
	En UserLocale = "en"
)

// Valid indicates whether the value is a known member of the UserLocale enum.
func (e UserLocale) Valid() bool {
	switch e {
	case Ar:
		return true
	case En:
		return true
	default:
		return false
	}
}

// Business defines model for Business.
type Business struct {
	// CrNumber Example: 1010123456
	CrNumber  string    `json:"cr_number"`
	CreatedAt time.Time `json:"created_at"`

	// DisplayName Text in Arabic (required) and English (optional).
	DisplayName LocalizedText      `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	LegalName   string             `json:"legal_name"`

	// Status `draft` → `pending_review` (submitted) → `active` (approved) or
	// `rejected` (fix and resubmit); `active` ↔ `suspended` by the platform.
	Status    BusinessStatus `json:"status"`
	UpdatedAt time.Time      `json:"updated_at"`

	// Version Increases on every change; send it as `If-Match` when editing.
	//
	// Example: 1
	Version int `json:"version"`
}

// BusinessRegistration defines model for BusinessRegistration.
type BusinessRegistration struct {
	// CrNumber 10-digit Commercial Registration number (Western or Arabic-Indic digits; spaces allowed).
	//
	// Example: 1010123456
	CrNumber string `json:"cr_number"`

	// DisplayName Text in Arabic (required) and English (optional).
	DisplayName LocalizedText `json:"display_name"`

	// LegalName The name on the Commercial Registration.
	//
	// Example: مؤسسة الأناقة للحلاقة
	LegalName string `json:"legal_name"`
}

// BusinessStatus `draft` → `pending_review` (submitted) → `active` (approved) or
// `rejected` (fix and resubmit); `active` ↔ `suspended` by the platform.
type BusinessStatus string

// BusinessSummary defines model for BusinessSummary.
type BusinessSummary struct {
	// DisplayName Text in Arabic (required) and English (optional).
	DisplayName LocalizedText      `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`

	// Status `draft` → `pending_review` (submitted) → `active` (approved) or
	// `rejected` (fix and resubmit); `active` ↔ `suspended` by the platform.
	Status BusinessStatus `json:"status"`
}

// LocalizedText Text in Arabic (required) and English (optional).
type LocalizedText struct {
	// Ar Example: صالون الأناقة
	Ar string `json:"ar"`

	// En Example: Elegance Barbers
	En *string `json:"en,omitempty"`
}

// Login defines model for Login.
type Login struct {
	// IsNewUser True when this verification created the account (show onboarding).
	IsNewUser bool      `json:"is_new_user"`
	Tokens    TokenPair `json:"tokens"`
	User      User      `json:"user"`
}

// Membership defines model for Membership.
type Membership struct {
	Business BusinessSummary    `json:"business"`
	Role     StaffRole          `json:"role"`
	StaffId  openapi_types.UUID `json:"staff_id"`
}

// MembershipList defines model for MembershipList.
type MembershipList struct {
	Data []Membership `json:"data"`
}

// OTPRequest defines model for OTPRequest.
type OTPRequest struct {
	// Phone Saudi mobile number in any common format (05…, +9665…, Arabic-Indic digits).
	//
	// Example: 0551234567
	Phone string `json:"phone"`
}

// OTPRequested defines model for OTPRequested.
type OTPRequested struct {
	// ExpiresInSeconds Example: 300
	ExpiresInSeconds int `json:"expires_in_seconds"`

	// ResendAfterSeconds Example: 60
	ResendAfterSeconds int `json:"resend_after_seconds"`
}

// OTPVerify defines model for OTPVerify.
type OTPVerify struct {
	// Code The 6-digit code (Western or Arabic-Indic digits).
	//
	// Example: 482193
	Code string `json:"code"`

	// Phone Example: 0551234567
	Phone string `json:"phone"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code. Known values:
	// `validation_failed`, `not_found`, `method_not_allowed`, `internal`,
	// `not_ready`, `rate_limited`, `otp_cooldown`, `otp_invalid`,
	// `otp_expired`, `otp_too_many_attempts`, `otp_locked`, `user_blocked`,
	// `unauthorized`, `refresh_token_invalid`, `refresh_token_reused`,
	// `forbidden`, `business_already_registered`.
	//
	//
	// Example: otp_cooldown
	Code      string  `json:"code"`
	Detail    *string `json:"detail,omitempty"`
	RequestId *string `json:"request_id,omitempty"`

	// Status Example: 429
	Status int `json:"status"`

	// Title Example: Too Many Requests
	Title string `json:"title"`

	// Type Example: about:blank
	Type string `json:"type"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// StaffRole defines model for StaffRole.
type StaffRole string

// TokenPair defines model for TokenPair.
type TokenPair struct {
	// AccessToken Send as `Authorization: Bearer <access_token>`.
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	//
	// Example: 900
	ExpiresIn int `json:"expires_in"`

	// RefreshExpiresIn Seconds until the refresh token expires if unused.
	//
	// Example: 2592000
	RefreshExpiresIn int `json:"refresh_expires_in"`

	// RefreshToken Single use. Store it in the device's secure storage only.
	RefreshToken string             `json:"refresh_token"`
	TokenType    TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Locale    UserLocale         `json:"locale"`

	// Name Example: عبدالرحمن
	Name *string `json:"name,omitempty"`

	// Phone Example: +966551234567
	Phone string `json:"phone"`
}

// UserLocale defines model for User.Locale.
type UserLocale string

// AcceptLanguage Example: ar-SA
type AcceptLanguage = string

// BusinessID defines model for BusinessID.
type BusinessID = openapi_types.UUID

// VerifyOTPParams defines parameters for VerifyOTP.
type VerifyOTPParams struct {
	// AcceptLanguage Preferred language (`ar` default, `en`). Also the language saved for new users.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// RequestOTPJSONRequestBody defines body for RequestOTP for application/json ContentType.
type RequestOTPJSONRequestBody = OTPRequest

// VerifyOTPJSONRequestBody defines body for VerifyOTP for application/json ContentType.
type VerifyOTPJSONRequestBody = OTPVerify

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = RefreshRequest

// RegisterBusinessJSONRequestBody defines body for RegisterBusiness for application/json ContentType.
type RegisterBusinessJSONRequestBody = BusinessRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Logout Sign out of this session
	// (POST /v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// RequestOTP Send a one-time login code by SMS
	// (POST /v1/auth/otp/request)
	RequestOTP(w http.ResponseWriter, r *http.Request)
	// VerifyOTP Check a one-time code and sign in (registering new numbers)
	// (POST /v1/auth/otp/verify)
	VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams)
	// RefreshTokens Exchange a refresh token for a new token pair
	// (POST /v1/auth/refresh)
	RefreshTokens(w http.ResponseWriter, r *http.Request)
	// RegisterBusiness Register a business (starts as a draft)
	// (POST /v1/businesses)
	RegisterBusiness(w http.ResponseWriter, r *http.Request)
	// GetBusiness A business, for its owner
	// (GET /v1/businesses/{business_id})
	GetBusiness(w http.ResponseWriter, r *http.Request, businessId BusinessID)
	// GetMe The signed-in user
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// ListMyMemberships The businesses the signed-in user works in, and their role
	// (GET /v1/me/memberships)
	ListMyMemberships(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Logout Sign out of this session
// (POST /v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RequestOTP Send a one-time login code by SMS
// (POST /v1/auth/otp/request)
func (_ Unimplemented) RequestOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyOTP Check a one-time code and sign in (registering new numbers)
// (POST /v1/auth/otp/verify)
func (_ Unimplemented) VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshTokens Exchange a refresh token for a new token pair
// (POST /v1/auth/refresh)
func (_ Unimplemented) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RegisterBusiness Register a business (starts as a draft)
// (POST /v1/businesses)
func (_ Unimplemented) RegisterBusiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetBusiness A business, for its owner
// (GET /v1/businesses/{business_id})
func (_ Unimplemented) GetBusiness(w http.ResponseWriter, r *http.Request, businessId BusinessID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe The signed-in user
// (GET /v1/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListMyMemberships The businesses the signed-in user works in, and their role
// (GET /v1/me/memberships)
func (_ Unimplemented) ListMyMemberships(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestOTP operation middleware
func (siw *ServerInterfaceWrapper) RequestOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyOTP operation middleware
func (siw *ServerInterfaceWrapper) VerifyOTP(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params VerifyOTPParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyOTP(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshTokens operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterBusiness operation middleware
func (siw *ServerInterfaceWrapper) RegisterBusiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterBusiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBusiness operation middleware
func (siw *ServerInterfaceWrapper) GetBusiness(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "business_id" -------------
	var businessId BusinessID

	err = runtime.BindStyledParameterWithOptions("simple", "business_id", chi.URLParam(r, "business_id"), &businessId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "business_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBusiness(w, r, businessId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyMemberships operation middleware
func (siw *ServerInterfaceWrapper) ListMyMemberships(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyMemberships(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/request", wrapper.RequestOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/verify", wrapper.VerifyOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/refresh", wrapper.RefreshTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/me/memberships", wrapper.ListMyMemberships)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/businesses", wrapper.RegisterBusiness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/businesses/{business_id}", wrapper.GetBusiness)
	})

	return r
}

type ProblemResponseHeaders struct {
	RetryAfter      *int
	WWWAuthenticate *string
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LogoutdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response LogoutdefaultApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOTPRequestObject struct {
	Body *RequestOTPJSONRequestBody
}

type RequestOTPResponseObject interface {
	VisitRequestOTPResponse(w http.ResponseWriter) error
}

type RequestOTP202JSONResponse OTPRequested

func (response RequestOTP202JSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOTPdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response RequestOTPdefaultApplicationProblemPlusJSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOTPRequestObject struct {
	Params VerifyOTPParams
	Body   *VerifyOTPJSONRequestBody
}

type VerifyOTPResponseObject interface {
	VisitVerifyOTPResponse(w http.ResponseWriter) error
}

type VerifyOTP200JSONResponse Login

func (response VerifyOTP200JSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOTPdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response VerifyOTPdefaultApplicationProblemPlusJSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokensRequestObject struct {
	Body *RefreshTokensJSONRequestBody
}

type RefreshTokensResponseObject interface {
	VisitRefreshTokensResponse(w http.ResponseWriter) error
}

type RefreshTokens200JSONResponse TokenPair

func (response RefreshTokens200JSONResponse) VisitRefreshTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokensdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response RefreshTokensdefaultApplicationProblemPlusJSONResponse) VisitRefreshTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterBusinessRequestObject struct {
	Body *RegisterBusinessJSONRequestBody
}

type RegisterBusinessResponseObject interface {
	VisitRegisterBusinessResponse(w http.ResponseWriter) error
}

type RegisterBusiness201JSONResponse Business

func (response RegisterBusiness201JSONResponse) VisitRegisterBusinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterBusinessdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response RegisterBusinessdefaultApplicationProblemPlusJSONResponse) VisitRegisterBusinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetBusinessRequestObject struct {
	BusinessId BusinessID `json:"business_id"`
}

type GetBusinessResponseObject interface {
	VisitGetBusinessResponse(w http.ResponseWriter) error
}

type GetBusiness200JSONResponse Business

func (response GetBusiness200JSONResponse) VisitGetBusinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBusinessdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetBusinessdefaultApplicationProblemPlusJSONResponse) VisitGetBusinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetMedefaultApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyMembershipsRequestObject struct {
}

type ListMyMembershipsResponseObject interface {
	VisitListMyMembershipsResponse(w http.ResponseWriter) error
}

type ListMyMemberships200JSONResponse MembershipList

func (response ListMyMemberships200JSONResponse) VisitListMyMembershipsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyMembershipsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response ListMyMembershipsdefaultApplicationProblemPlusJSONResponse) VisitListMyMembershipsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Logout Sign out of this session
	// (POST /v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RequestOTP Send a one-time login code by SMS
	// (POST /v1/auth/otp/request)
	RequestOTP(ctx context.Context, request RequestOTPRequestObject) (RequestOTPResponseObject, error)
	// VerifyOTP Check a one-time code and sign in (registering new numbers)
	// (POST /v1/auth/otp/verify)
	VerifyOTP(ctx context.Context, request VerifyOTPRequestObject) (VerifyOTPResponseObject, error)
	// RefreshTokens Exchange a refresh token for a new token pair
	// (POST /v1/auth/refresh)
	RefreshTokens(ctx context.Context, request RefreshTokensRequestObject) (RefreshTokensResponseObject, error)
	// RegisterBusiness Register a business (starts as a draft)
	// (POST /v1/businesses)
	RegisterBusiness(ctx context.Context, request RegisterBusinessRequestObject) (RegisterBusinessResponseObject, error)
	// GetBusiness A business, for its owner
	// (GET /v1/businesses/{business_id})
	GetBusiness(ctx context.Context, request GetBusinessRequestObject) (GetBusinessResponseObject, error)
	// GetMe The signed-in user
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// ListMyMemberships The businesses the signed-in user works in, and their role
	// (GET /v1/me/memberships)
	ListMyMemberships(ctx context.Context, request ListMyMembershipsRequestObject) (ListMyMembershipsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestOTP operation middleware
func (sh *strictHandler) RequestOTP(w http.ResponseWriter, r *http.Request) {
	var request RequestOTPRequestObject

	var body RequestOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestOTP(ctx, request.(RequestOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestOTPResponseObject); ok {
		if err := validResponse.VisitRequestOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyOTP operation middleware
func (sh *strictHandler) VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams) {
	var request VerifyOTPRequestObject

	request.Params = params

	var body VerifyOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyOTP(ctx, request.(VerifyOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyOTPResponseObject); ok {
		if err := validResponse.VisitVerifyOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshTokens operation middleware
func (sh *strictHandler) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokensRequestObject

	var body RefreshTokensJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshTokens(ctx, request.(RefreshTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokensResponseObject); ok {
		if err := validResponse.VisitRefreshTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterBusiness operation middleware
func (sh *strictHandler) RegisterBusiness(w http.ResponseWriter, r *http.Request) {
	var request RegisterBusinessRequestObject

	var body RegisterBusinessJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterBusiness(ctx, request.(RegisterBusinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterBusiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterBusinessResponseObject); ok {
		if err := validResponse.VisitRegisterBusinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBusiness operation middleware
func (sh *strictHandler) GetBusiness(w http.ResponseWriter, r *http.Request, businessId BusinessID) {
	var request GetBusinessRequestObject

	request.BusinessId = businessId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBusiness(ctx, request.(GetBusinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBusiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBusinessResponseObject); ok {
		if err := validResponse.VisitGetBusinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyMemberships operation middleware
func (sh *strictHandler) ListMyMemberships(w http.ResponseWriter, r *http.Request) {
	var request ListMyMembershipsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyMemberships(ctx, request.(ListMyMembershipsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyMemberships")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMyMembershipsResponseObject); ok {
		if err := validResponse.VisitListMyMembershipsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xHvdbhtJdv+rHPT/DwyFoShKlrxj+krWeCZO7IwgaTIXpsEudh+ya9xd1VNVLZprCFgEs0aug32DBNns",
	"xSIIFrnIm0i38yTBOdWfZOvDE3tzJ5JVdarOOb/f+ajS+yDSWa4VKmeDyfsgF0Zk6NDwp+Mowty9FGpZ",
	"iCXSNzHayMjcSa2CSXBqcIHGYAxpOQYGoTAhxLgQReqGEKIKd0ZwnFoNLsFmnBWXGMNCG1C4gsKisaNg",
	"GEhaNkERowmGgRIZBpNyG7v1PoaBjRLMBG0I34ksT2mUMLvnx8EwcOucPlpnpFoGV1fD4FlhpUJrX3xN",
	"M1hELlzSCJiXA2YyDoaBwZ8KaTAOJs4U2Ba20CYTLpgERSHjHlFXNNnmWllk/Z0aPU8xoz8jrRwqR3+K",
	"PE9lJEiHe7kf8eWPlhT6viXr/xtcBJPg/+01Btrzv9q9al2W2DXJc2O0gcHZNyfw5PDoN1AKgBidkKnd",
	"CYalenmDZ+jMevd44dBsW/ccI61iC07DSkgHc1xog2BojlRLGGiVrkErODx4stMxSqkXqRwu0bANfvjh",
	"h93jwiWoHJ29x5meoTBoIEpEmqJaYmv98T4sjM7oMA4jhzHoHA1r0PZKbixydVX9zAeuXIH+zg2t4qS3",
	"VWRmqsjmaLpetT/eH+8fPDo8erxt72EQGRQO45lwHfeIhcNdJzPsmxNLm6diPfO+d7ehX+pIpPK3GF/g",
	"O0eTZfwAPxwGKS5FWkvY+tk64Qp7n/BKV+d+9NUwKPL4o497icZKrbbt/UKR9ixaMjFeolmT7dUSn4JF",
	"FYN0ICyELxa7r4SLkhBWCSrAWDqplsQVtZH2h30e18D4dcBa6ii+o6Nhy/q1dpqtd+zc0cKbWrKe/4gR",
	"m6hS2xkupXXeSxn2MW1dK5GethxvIVKLw7t8sau1/fFuLJfSwYnOMjSRFCm0JYGfCIMf0Do0CrSBYyPm",
	"Mtp9oWIZAc+2T8HmIkILIk31CuOdjkK7Xp+Jdy9RLV0STA7GwyCTqvq4P/7U/t113O7RLxIE+oX8hWLJ",
	"LRronuTm99f/ev2X679c/wmu/3jz8/W/3Hy4/uPNP17/CW5+vvn5+s83P/uPm+fcOGhfWGk72MN86y53",
	"Oa8x2T11GBuxcCH88uGfIcxRxVItZwYvJa5CGNhinknnMN7xA0Tk5CWGMBB5bvQlfa/NVIUGf2TiDGGw",
	"kO9AqBgM+sk7T5tpv3z4A4S2sCSHBs/XrOk8FY7QPpoSGFAVGZ+ZNhYMg+6mgmHgV+NI6qUSqKpFgzdb",
	"umwpocgyYdbb7PzXIM1fx4oPYJpy4T7rd/d6H0ts4AHfOZCqhDcMqm3ssHmfq2UqbQIDnfv1GOJdrYqN",
	"YHf9X4SRm3+6+bABli469u9FBzlJd+nnBAkVITwTZo7G9qx4N8KEuUWBS6m2/UXamcLVrLB9HHphCvTR",
	"xCXSwiUauSgTMiiZnt1eRJEulIOBTfQKtJprYcjTWZPlTuZapygUbcXpt6ju9Z8LGnUqpOGAWu7vrgnf",
	"256AxhOHnWPWG+hT0yskArKJzLd1NW/lRA/y/BKktCWd3gvHcycWizMa6DG2WMweBMiNE9e7bC1SbuDu",
	"A7+U1vUQinCcMEqH2b0nbxYLrmpZwhix3g4EtG7fhr67OD3Dnwq07iOTgTzRqicanosilpDpuUyxCvpS",
	"gVBriHSWaQVevzAYH/3yu38bwpdPHj/2f/XkAxvxf3x05MP/b7o4fXz4cWHR7/1udWC8bR18l0uDdibV",
	"zPoqpMMmj8bj7ZSPJFtU8UxQOdM77/H43kyxR/ItC99yqn8gNll/bMKn41sSnsdlukcj7kvqNox4+NXB",
	"/pNHGwbs2O9xD3HX7va5vGHoT9unvla9/BD9nDsxTxEyESVS4a5BEfMXyDUwzRnB3ym9UnAp0gLtZKrC",
	"S5HKmKl+thAyxTgcQqi0my10ofhDhi7R8Yy+K5Nj+pb8xSiRhsOp4vEkbU2/GOFwlspMOj9Su3wWaZ3G",
	"eqWqz1KxXJ5Mn72X1cOd1rNMqPVMOIdZ7mz1Q6qjt34YUfxsXn2eqrBQonCJNvK3foDBhUGbzDgINAI3",
	"fzBY2HKFhTZzGcfIu6xbICLlk80Mp9RIuyzTvtof2ifsrXC519BbeRqP+TIC3JGC1dIOD570Yd1Jl264",
	"6YXW8Ir4ryQW27c3/0V7mpjrwk3mqVBv7w1C/GslvFUp3urRZ175v475O5ajL9oVytHjjwNfd7G+vTaB",
	"evK+TvL1SnFukQkllvzXnBO43jS+yW22ECyiiLyrPsoGklHFXO0flz7NCJ1A2ROaFuPxo6i9BH+D4ajP",
	"xA2F397TKpSTaZXkobXAq0I5tcOjT24LNl6fHyetnNUVB3IBhSJcdgQfHD05GN8t/DZ1SrVMEQqLIzh3",
	"2iBIrhRoBzFeygi/sGAxKgyCddpQQ5aabb3q9LxR46b0C2+ZHi/YTNvbdu8s1jHU5pF69dvntN9b7PG2",
	"X9OXe2hrjSq2jioEoaKDqWZ0Va+2aqz/vv736//g8uo/r/988/ubD8EwUEWaUuiqWs4Picqcz7UC8912",
	"4MNUAbg8Q6evta1c4mPyEenW55QIl9UCG55w2nz6plLa3/5wEWyWqcdtgHEbN+S/7ajtG9TLkEu1Kzm5",
	"KY3PCQ0n4VxqsazmpIlzuW+BS7XQ2yj4m4uLUzg+fcG3DOT6nrlsonOYa/2WethVZwMGPp/mrErAHnx7",
	"crIzmqoLKhAXlGJLy2tYXZgIQS/AmcIlE/7yWw0WzSVn4A7NQkQ8fokKDVeTdOypkg4GYSbeYv1LuDPk",
	"Yt1qWMnUU8Q3aeEcGohSicrBHEdwwn1RLz/HaKoW0lg3pC88qH2uc6LVJSo6vZ1ArCO7J3K5py/RUGNm",
	"lMWjqZoqviGwIAxCfUsQ3nYnEcJKugQEWJ9rhSQp5HVa3Xzmat/CrRvzoBDjj2f0qSpUitYSY8UYpcKg",
	"hbDywwm8fhOOoO1SFlJ5ibB/BJlUhUP7FAwqXE2VSzDz2w9Pvzu/gL3L/T3KmfZK76KFIKTLhU4u5X1U",
	"NJcNU9UcKkOhLEwrdipNwFcioFWE08AnS2V6EjxrXO749EWrpzwJxqP90ZiwrXNUIpfBJHg0Go8oYafb",
	"KQZbveVUL3Xhy1ht3bavP+eLGvIEuj0xTO/WssalsxthxzqdW1hpwxAQjnfOzo4QFcagct2waJ1YW+CM",
	"soxl0tXBayAcZNo62D+aqtIGO0MoL/xEnoNNdJHGEBud00Sn9QhORJqSdPq8kh4vC6nQq69W+Is4mAQv",
	"/eE3LtcOxod9kW+pMAYazokoX0PeVt7Xy7Uu1KhTWfYgeTFaitGeyFqnZF+xtMz9xINvaFptKu3yPdPk",
	"e/32ooTHguiWd86rjFm6LOlHQEYRyq7Q1BQkMpyqVYIuQUNsqbTjH/wUKDN4SIQFoaouVm0RVHGupXJT",
	"FQn1BREMUOpB0mNpI6ILWCWapDU1ACP+JRU5dgK0Pd5wjqYSSn+GfXVy6BlOwIIwSdPs5rxEFwYG4eHB",
	"E+gUT7AH/GWnwmJWpkjC1VuneWcZ7VK1yACoYmorh2JB8/NUNWLrWstTRutqlFhaqigtqPkHpW1tfXnN",
	"Z+rz2zLr/+7iNKgrn2c6Xt9xH/xx98CtntJVN+A7U+DVFmAOPoNkjPuuoU/IPSyJ+dUwLCk/mLx+0wEl",
	"lwrkg5zJQUoNYO+O8zWcvzq/H52XdYumH5zHEGljMCphSXmJR15hOcQ/BVG5k0VUdX7BURloV1M1x0hn",
	"SBCv3jfAIGy1ayeUPyC9jXguosQLIka2TMbDil2nisHk4VM7NQOKehO2/KHqG7A/j/eh03OA+qtW26Hy",
	"+u3Ww/8JwEbw9xWSINbMaAYtOt5FYdA+nSoBtuCotCjSzraIA/lo5aeFt4afCSupYr2CWDNIp4pYnSMP",
	"xzXjSId1sPQ1mvdHiIQxEisSbcKhUDHtphtUB2VWG+70UYHvCnomaL+xed0PiWbI3sYbnKs3n41K/B4f",
	"xiTjTybYX+D0UEgZyqX65BRykmD0ts0hjD7OwyniSwWDKvKRoxCAvXPbnbvJpfSIO9I0zpG7jtOg3rtf",
	"Gexr52P5nSmU2goHBvOU7/ClG8Epx17HCZ2qUoBdDuxdcT6DlW6qVsJCpHOJcZ0brBKdYoUGkBb4yhY8",
	"qfQ2EnemihRXs2NWWFerUSyFVCP4Xr2lLmxFajHh1bJ1dym78riZqiU66BFU8RiD94SLIuvFeJYoD+eT",
	"SAUEnTTF1LNMlS9VIF3QbXhZQ4Nb6Saas0rn2iWw1H4f4Y43iE9kOLOGFWeyqdZvpyqVbxFYDSM4T4RB",
	"ToyqDc3RrRApMqkqp65k9ecKPI07aPYzpQsbzci/MtBbF5/bYCf2937wydH+/J1/VgSbjE2RyqPLf85p",
	"b7fhu+qPo70d3SfcTSHIVqPJIasHHL5Z3Lilr9RAWK7QuM86mqpj4OGEvdzIS+G4LKARfOv5FKLCOp2h",
	"sWARCQIJYb7uME5V3dIon4DQ+uVDEQ9r//iDWgJAHHOJkArnbw9fPdphmFHRcXJWvyXyvZFb3tsMYX9c",
	"XUDRtiNiV6qaSb/lHSQ3F+EFHytKhcwwhl9+9wfIRIxQKPlTgSAio63tvDehMVzp+C5Ho1UL9cMXNqM/",
	"DtOY0nMdryESCvi6BMRUGRQp+L7PGtrUTnqtqiaym9f94Pjrs93xeP9oZwRnzeipqtmk0Y3nHdFUZt6S",
	"vnpaMP+SxacqPBw/gbtuWYawSmSUgEitBuoSWfZYZyRzOGN2qqxY4ARSaR2E5JcZ7mX17bQNyVkWsiTk",
	"Slo/33jBz5pr9c9BOb2P4R5EPPuffA99vHNW6/8T9AuqxdoEMKhyzNq92jlEi1V6mGbvfeth8hXtaok9",
	"tPMdO5yH2AmTiuUCXhjmB08cVVZcb2yJjp3yEJrbT8Zk7chlIiJsyZT1VA6VlE+rLxxFU2l9d+HF1xbq",
	"ngJ1ETGm+weSThjgWJ9UADGUaVSbeATNZWSft36LruOonylE3eUpFy3lfQJfOa4XG7J66xhwm3d8bN3Q",
	"evR+9aZ0rQxbTrSl4Vf4OXVbPmPq1Su/X/rf65SWKvNKqaCwHWVm2ECsS5q3AutrCo62amN+QX3fSquQ",
	"6RinAdiVdFEyAaGAque1Z2afY1c58VRJy/AEUUfvEfhSoMaU4KF1cLIkEYWxkKDBMoTQggybkD2F+9c8",
	"a46pVkt+qS8gESqmClkvoHEgKJu0w6mq/hODNiotM0QullIJh3Ef9uj91Kv1q5a+PqOXbDzbusVfWsYb",
	"UgKH1jWa5C7MJ/KmlgLdlnOVlZtUvsPpEpSe1ra8rpuddu/QXr+hkt5fH3lgd8/LL0Tp1hZTnWeo+AW6",
	"Scv7r8neHl/mJdq6yVfjr8bcICilb/27TquxDF9ulL/cRxtWdyp0oLIMtM3/yXBKfDXse6e0hbtySoY9",
	"Ezoo4qBj6tBJyWmhKNy0buvqaOpQCeV2mvUbCxHN/c8A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
