// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserLocale.
const (
	Ar UserLocale = "ar"
	En UserLocale = "en"
)

// Valid indicates whether the value is a known member of the UserLocale enum.
func (e UserLocale) Valid() bool {
	switch e {
	case Ar:
		return true
	case En:
		return true
	default:
		return false
	}
}

// Login defines model for Login.
type Login struct {
	// IsNewUser True when this verification created the account (show onboarding).
	IsNewUser bool `json:"is_new_user"`
	User      User `json:"user"`
}

// OTPRequest defines model for OTPRequest.
type OTPRequest struct {
	// Phone Saudi mobile number in any common format (05…, +9665…, Arabic-Indic digits).
	//
	// Example: 0551234567
	Phone string `json:"phone"`
}

// OTPRequested defines model for OTPRequested.
type OTPRequested struct {
	// ExpiresInSeconds Example: 300
	ExpiresInSeconds int `json:"expires_in_seconds"`

	// ResendAfterSeconds Example: 60
	ResendAfterSeconds int `json:"resend_after_seconds"`
}

// OTPVerify defines model for OTPVerify.
type OTPVerify struct {
	// Code The 6-digit code (Western or Arabic-Indic digits).
	//
	// Example: 482193
	Code string `json:"code"`

	// Phone Example: 0551234567
	Phone string `json:"phone"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code. Known values:
	// `validation_failed`, `not_found`, `method_not_allowed`, `internal`,
	// `not_ready`, `rate_limited`, `otp_cooldown`, `otp_invalid`,
	// `otp_expired`, `otp_too_many_attempts`, `user_blocked`.
	//
	//
	// Example: otp_cooldown
	Code      string  `json:"code"`
	Detail    *string `json:"detail,omitempty"`
	RequestId *string `json:"request_id,omitempty"`

	// Status Example: 429
	Status int `json:"status"`

	// Title Example: Too Many Requests
	Title string `json:"title"`

	// Type Example: about:blank
	Type string `json:"type"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Locale    UserLocale         `json:"locale"`

	// Name Example: عبدالرحمن
	Name *string `json:"name,omitempty"`

	// Phone Example: +966551234567
	Phone string `json:"phone"`
}

// UserLocale defines model for User.Locale.
type UserLocale string

// AcceptLanguage Example: ar-SA
type AcceptLanguage = string

// VerifyOTPParams defines parameters for VerifyOTP.
type VerifyOTPParams struct {
	// AcceptLanguage Preferred language (`ar` default, `en`). Also the language saved for new users.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// RequestOTPJSONRequestBody defines body for RequestOTP for application/json ContentType.
type RequestOTPJSONRequestBody = OTPRequest

// VerifyOTPJSONRequestBody defines body for VerifyOTP for application/json ContentType.
type VerifyOTPJSONRequestBody = OTPVerify

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// RequestOTP Send a one-time login code by SMS
	// (POST /v1/auth/otp/request)
	RequestOTP(w http.ResponseWriter, r *http.Request)
	// VerifyOTP Check a one-time code and sign in (registering new numbers)
	// (POST /v1/auth/otp/verify)
	VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// RequestOTP Send a one-time login code by SMS
// (POST /v1/auth/otp/request)
func (_ Unimplemented) RequestOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyOTP Check a one-time code and sign in (registering new numbers)
// (POST /v1/auth/otp/verify)
func (_ Unimplemented) VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestOTP operation middleware
func (siw *ServerInterfaceWrapper) RequestOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyOTP operation middleware
func (siw *ServerInterfaceWrapper) VerifyOTP(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params VerifyOTPParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyOTP(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/request", wrapper.RequestOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/verify", wrapper.VerifyOTP)
	})

	return r
}

type ProblemResponseHeaders struct {
	RetryAfter *int
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type RequestOTPRequestObject struct {
	Body *RequestOTPJSONRequestBody
}

type RequestOTPResponseObject interface {
	VisitRequestOTPResponse(w http.ResponseWriter) error
}

type RequestOTP202JSONResponse OTPRequested

func (response RequestOTP202JSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOTPdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response RequestOTPdefaultApplicationProblemPlusJSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOTPRequestObject struct {
	Params VerifyOTPParams
	Body   *VerifyOTPJSONRequestBody
}

type VerifyOTPResponseObject interface {
	VisitVerifyOTPResponse(w http.ResponseWriter) error
}

type VerifyOTP200JSONResponse Login

func (response VerifyOTP200JSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOTPdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response VerifyOTPdefaultApplicationProblemPlusJSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// RequestOTP Send a one-time login code by SMS
	// (POST /v1/auth/otp/request)
	RequestOTP(ctx context.Context, request RequestOTPRequestObject) (RequestOTPResponseObject, error)
	// VerifyOTP Check a one-time code and sign in (registering new numbers)
	// (POST /v1/auth/otp/verify)
	VerifyOTP(ctx context.Context, request VerifyOTPRequestObject) (VerifyOTPResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RequestOTP operation middleware
func (sh *strictHandler) RequestOTP(w http.ResponseWriter, r *http.Request) {
	var request RequestOTPRequestObject

	var body RequestOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestOTP(ctx, request.(RequestOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestOTPResponseObject); ok {
		if err := validResponse.VisitRequestOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyOTP operation middleware
func (sh *strictHandler) VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams) {
	var request VerifyOTPRequestObject

	request.Params = params

	var body VerifyOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyOTP(ctx, request.(VerifyOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyOTPResponseObject); ok {
		if err := validResponse.VisitVerifyOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFjNbiO5EX6VAhMgMqYtyR6Pd9w5eY3dzSBerDH2JoeVoaaaJTXX3cVeki2NMBCQQ5JHSXIJghzzJp5r",
	"niQosvVn9TizwM5NTRZZxaqvvqrSe5GbqjaE5J1I34taWlmhRxu+LvMca38tadbIGfKKQpdbXXttSKTi",
	"xuIUrUUFZSsDvUzaDBROZVP6BDKk7KgPl6Uz4Avcyjk5RwVTY4FwAY1D6/oiEZqvLVAqtCIRJCsUaWvG",
	"8caORLi8wEqyQfhOVnXJUtIe316KRPhlzZ/OW00zsVqtEmHR1YYchkfdWDMpseKfuSGP5PmnrOtS55If",
	"NqijxIsfHb/y/Y62X1ucilT8arD12iDuusH63qBx309fWWss9N5+fQUXZ6++gFYBKPRSl+5IJO2bg4Fv",
	"0dvl8eXUoz10+S3mhpQDb2AhtYcJTo1FsHxG0wx6hsolGIKz04ujPU+1ftHkcYaWzVyt1vtB77WZ6fDe",
	"2poardfRX9qNCRdjDtGhOXe2QVgUSOAL7WCOVk9bN0JuUXpUIe4yz01DHnquMAswNDHSKk2zo/42YhNj",
	"SpQkVolYK3vO39+78AqO7k+NtqhE+kM8mOzZfL9RYCY/Yu75/u/ubt7iTw26GHulNFssy5udl09l6TB5",
	"4oy6MNSRCLeyURoqM9ElAjXVBC1oAklLyE1VGWKkV9JDb/jqv3/6WwIvLs7P469LKyc6P35DSueg9Ex7",
	"F5yyBfbw1auT05dnr86/EImo5LtrpJkvRHp+lohK0/rz5BD6+76Jtj/vDlSHAMB3tbboxprGLqJvL/Fe",
	"DofJAbhCziGpsWQYd5477zj2xOIOzR+5+COv+gPjcfkzY5wb1RHiuwLh/DgECFgCen9kf1kCYz8hiGev",
	"T08uXj4J4F78zg/il2zh9rnQkMTXdrlvhyc/xT+3Xk5KhErmhSY8tihVWMDAfXymD78nsyCYy7JBl44o",
	"m8tSq0AW46nUJaosgYyMH09NQ+GjQl8YNeY1WZZmEUUYL5ZkmSUjCvKsbck7Vnocl7rSPkoaX49zY0pl",
	"FrT+1hT0hsP8HVG2EffGjCtJy7H0HqvaO95gJhlPSpM/oMr6I9qL7a4S0RHFSPM7HLzdsjHtxlp1bjsv",
	"fbOfNmenF13p5rUvnyDlzhj4limozW3XZVtc2D0mJ6bx6aSU9CD+H4jC7lr5xtxnQPV9S+xPEBUrxVgG",
	"Oo5UKVKhpMdjryvsMlyrPdmm0apLrDS5bB1DTcU2SysSgSTuO6Rjw7Hrjcf/PP7j8V+Pf//w58d/P/7z",
	"w18+/FUkgpqyZHCL1NsGPy1vA+PvpO7zjg2PWado+4Zk10+HzuUrNE3NYWr+7u7uBi5v3oR2i6vxRNoJ",
	"WleYGibGPHDfUJfSszOhF2tZYDQJA/jm6uqoP6I7Lu9TLm/ahTucaWyOYKbgbeOLNCx+Y8ChnYfq59FO",
	"ZR7kZ0hoQy8wtaYakfbQyyr5gJud7CgBSQqcgYUuy3DZ12XjPVrIS43EnU4frgpJM4z6a8xHNNXW+QR8",
	"7ECw5ZkrQ3Mkfr1LQZncDWStB2aOdq5x0a9Uf0QjCl2ZA2kRNp1Z9rE+MIOF9gVIcJHnMtbUMkGbe+LL",
	"rVsvb96IRMzRuhiCYf+kP2RkmBpJ1lqk4mV/2OeCUEtfhCwYzE8GsvHFwPh6YLftSW2cPwzqLXIbKPdr",
	"ko9ddgBO24f0gSuXJLdAu4mdrHBEiwJ9gZbrFxkfNuIRkGUgVCikA0nr5i2BtolHUrXR5EeUS/oNR4Yb",
	"eMXalXY5+xkWhWFtFmeaqyRGl18zM7sU2LxgcI12rZR/Zl3FPYvQkDDFxYj4mHt6rjCNhV52dnoBe4wP",
	"AwiLe2XhKEaNCSjE+Y0SqWg58ru7G7Fh5S+NWj4zJvy88WCn5VztZztzyNMh5XR4+hk0o+qaTq44EI7V",
	"hK0wuX3szo2RO+NOIlxTVdIuW1SC5PgG4oaSZ4oY6skSbr+9FYnwcuYCETe+EPd8fg/5803P1g38S8iN",
	"tZi3kHd6RhHVXKNB029BrqHhEGlDeoEqgK0a0QRzUyGnz3r6hF62MzSkTGrIk+tXMi+iooWxDw4M5ZhA",
	"25iOKAA1QhMqTY3nS9kF3Ky4dmPdSIyol50NT2CvCYHN0k4fsgbyYS/SCd7Y5kbs7k7wP3QHcSsyeDLh",
	"r+4/G/ijjZ+G/eEvpjjOtB2gv9UzQgWafgHQXxWYP+yiPuAllDM9Ix4Ee2se5FLLkIsAdUcd6cBXhxoa",
	"A7hv9jW3AqBwjqWpKyQvEtHYUqSi8L5OB4PQKxTG+fT18PUwBLRVcPDnzU6RgBdPjA95u/0HJti2ul/9",
	"bwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
