// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserLocale.
const (
	Ar UserLocale = "ar"
	En UserLocale = "en"
)

// Valid indicates whether the value is a known member of the UserLocale enum.
func (e UserLocale) Valid() bool {
	switch e {
	case Ar:
		return true
	case En:
		return true
	default:
		return false
	}
}

// Login defines model for Login.
type Login struct {
	// IsNewUser True when this verification created the account (show onboarding).
	IsNewUser bool `json:"is_new_user"`
	User      User `json:"user"`
}

// OTPRequest defines model for OTPRequest.
type OTPRequest struct {
	// Phone Saudi mobile number in any common format (05…, +9665…, Arabic-Indic digits).
	//
	// Example: 0551234567
	Phone string `json:"phone"`
}

// OTPRequested defines model for OTPRequested.
type OTPRequested struct {
	// ExpiresInSeconds Example: 300
	ExpiresInSeconds int `json:"expires_in_seconds"`

	// ResendAfterSeconds Example: 60
	ResendAfterSeconds int `json:"resend_after_seconds"`
}

// OTPVerify defines model for OTPVerify.
type OTPVerify struct {
	// Code The 6-digit code (Western or Arabic-Indic digits).
	//
	// Example: 482193
	Code string `json:"code"`

	// Phone Example: 0551234567
	Phone string `json:"phone"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code. Known values:
	// `validation_failed`, `not_found`, `method_not_allowed`, `internal`,
	// `not_ready`, `rate_limited`, `otp_cooldown`, `otp_invalid`,
	// `otp_expired`, `otp_too_many_attempts`, `user_blocked`.
	//
	//
	// Example: otp_cooldown
	Code      string  `json:"code"`
	Detail    *string `json:"detail,omitempty"`
	RequestId *string `json:"request_id,omitempty"`

	// Status Example: 429
	Status int `json:"status"`

	// Title Example: Too Many Requests
	Title string `json:"title"`

	// Type Example: about:blank
	Type string `json:"type"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Locale    UserLocale         `json:"locale"`

	// Name Example: عبدالرحمن
	Name *string `json:"name,omitempty"`

	// Phone Example: +966551234567
	Phone string `json:"phone"`
}

// UserLocale defines model for User.Locale.
type UserLocale string

// AcceptLanguage Example: ar-SA
type AcceptLanguage = string

// VerifyOTPParams defines parameters for VerifyOTP.
type VerifyOTPParams struct {
	// AcceptLanguage Preferred language (`ar` default, `en`). Also the language saved for new users.
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// RequestOTPJSONRequestBody defines body for RequestOTP for application/json ContentType.
type RequestOTPJSONRequestBody = OTPRequest

// VerifyOTPJSONRequestBody defines body for VerifyOTP for application/json ContentType.
type VerifyOTPJSONRequestBody = OTPVerify

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// RequestOTP Send a one-time login code by SMS
	// (POST /v1/auth/otp/request)
	RequestOTP(w http.ResponseWriter, r *http.Request)
	// VerifyOTP Check a one-time code and sign in (registering new numbers)
	// (POST /v1/auth/otp/verify)
	VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// RequestOTP Send a one-time login code by SMS
// (POST /v1/auth/otp/request)
func (_ Unimplemented) RequestOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyOTP Check a one-time code and sign in (registering new numbers)
// (POST /v1/auth/otp/verify)
func (_ Unimplemented) VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestOTP operation middleware
func (siw *ServerInterfaceWrapper) RequestOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyOTP operation middleware
func (siw *ServerInterfaceWrapper) VerifyOTP(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params VerifyOTPParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyOTP(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/request", wrapper.RequestOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/verify", wrapper.VerifyOTP)
	})

	return r
}

type ProblemResponseHeaders struct {
	RetryAfter *int
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type RequestOTPRequestObject struct {
	Body *RequestOTPJSONRequestBody
}

type RequestOTPResponseObject interface {
	VisitRequestOTPResponse(w http.ResponseWriter) error
}

type RequestOTP202JSONResponse OTPRequested

func (response RequestOTP202JSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOTPdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response RequestOTPdefaultApplicationProblemPlusJSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOTPRequestObject struct {
	Params VerifyOTPParams
	Body   *VerifyOTPJSONRequestBody
}

type VerifyOTPResponseObject interface {
	VisitVerifyOTPResponse(w http.ResponseWriter) error
}

type VerifyOTP200JSONResponse Login

func (response VerifyOTP200JSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOTPdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response VerifyOTPdefaultApplicationProblemPlusJSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// RequestOTP Send a one-time login code by SMS
	// (POST /v1/auth/otp/request)
	RequestOTP(ctx context.Context, request RequestOTPRequestObject) (RequestOTPResponseObject, error)
	// VerifyOTP Check a one-time code and sign in (registering new numbers)
	// (POST /v1/auth/otp/verify)
	VerifyOTP(ctx context.Context, request VerifyOTPRequestObject) (VerifyOTPResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RequestOTP operation middleware
func (sh *strictHandler) RequestOTP(w http.ResponseWriter, r *http.Request) {
	var request RequestOTPRequestObject

	var body RequestOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestOTP(ctx, request.(RequestOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestOTPResponseObject); ok {
		if err := validResponse.VisitRequestOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyOTP operation middleware
func (sh *strictHandler) VerifyOTP(w http.ResponseWriter, r *http.Request, params VerifyOTPParams) {
	var request VerifyOTPRequestObject

	request.Params = params

	var body VerifyOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyOTP(ctx, request.(VerifyOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyOTPResponseObject); ok {
		if err := validResponse.VisitVerifyOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFjNbiO5EX6VAhMgMqYtyR7bO+6cvMbuZhAv1hh7k8NqoKaaJTXX3cVeki2NMDCQQ5JHSXIJghzzJp5r",
	"niQosvXf48wCOyerySKrWPVV1Vd+L3JT1YaQvBPpe1FLKyv0aMPXVZ5j7W8kzRo5Q15R6HKra68NiVTc",
	"WpyitaigbGWgl0mbgcKpbEqfQIaUHfXhqnQGfIEbOSfnqGBqLBAuoHFoXV8kQvO1BUqFViSCZIUibc04",
	"XtuRCJcXWEk2CN/Jqi5ZStrjuyuRCL+s+dN5q2kmHh8fE2HR1YYchkfdWjMpseKfuSGP5PmnrOtS55If",
	"NqijxIsfHb/y/Za2X1ucilT8arDx2iDuusHq3qBx109fWWss9N58fQ2XZ+dfQKsAFHqpS3ckkvbNwcA3",
	"6O3y+Grq0R66/A5zQ8qBN7CQ2sMEp8YiWD6jaQY9Q+USDMHZ6eXRjqdav2jyOEPLZrKhrfUscGNmOry3",
	"tqZG63X0l3ZjwsWYQ3Rozr1tEBYFEvhCO5ij1dPWjZBblB5ViLvMc9OQh54rzAIMTYy0StPsqL+J2MSY",
	"EiWJx0SslD3n7+9deAVH96dGW1Qi/SEeTHZsfrtWYCY/Yu75/u/ub9/gTw26GHulNFssy9utl09l6TDZ",
	"c0ZdGOpIhDvZKA2VmegSgZpqghY0gaQl5KaqDDHSK+mhNzz/75/+lsCLy4uL+OvKyonOj1+T0jkoPdPe",
	"BadsgD08Pz85fXl2fvGFSEQl390gzXwh0ouzRFSaVp8nh9Df9U20/Xl3sOQ+APBdrS26saaxi+jbSbyX",
	"w2FyAK6Qc0hqLBnGnecuOo7tWdyh+SMXf+RVf2A8Ln9mjHOjOkJ8XyBcHIcAAUtA74/sL0tg7CcE8ezV",
	"6cnly70A7sTv4iB+yQZunwsNSXxtl/u26uSn+OfOy0mJUMm80ITHFqUKCxhqH5/pw+/JLAjmsmzQpSPK",
	"5rLUKhSL8VTqElWWQEbGj6emofBRoS+MGvOaLEuziCKMF0uyzJIRBXnWtuQdKz2OS11pHyWNr8e5MaUy",
	"C1p9awp6w2H+jihbi3tjxpWk5Vh6j1XtHW9wJRlPSpM/oMr6I9qJ7bYS0RHFWOa3avBmy8a0G2vVue28",
	"9M1u2pydXnalm9e+3EPKvTHwLZegNrddl21xYaePTkzj00kp6UH8PxCF3ZXytbnPgOr7trDvISp2irEM",
	"5TiWSpEKJT0ee11hl+HRY2vZptGqS6w0uWwdQ03FNktuEEhb5m2kI+HY9sbTf57+8fSvp79/+PPTv5/+",
	"+eEvH/7KvKQpSwa3SL1t8NPyNlT8rdR93rHhMasUbd+QbPvp0Ll8haapOUzN393f38LV7etAt7gbT6Sd",
	"oHWFqWFizAPzhrqUnp0JvdjLQkWTMIBvrq+P+iO65/Y+5famXbjDmcbmCGYK3ja+SMPiNwYc2nnofh7t",
	"VOZBfoaENnCBqTXViLSHXlbJB1zvZEcJSFLgDCx0WYbLvi4b79FCXmokZjp9uC4kzTDqrzEf0VRb5xNe",
	"oLAa68y1oTkSv96loEzuBrLWAzNHO9e46FeqP6IRBVbmQFqENTPLPsYDM1hoX4AEF+tcxpraStDmnvhy",
	"49ar29ciEXO0LoZg2D/pDxkZpkaStRapeNkf9rkh1NIXIQsG85OBbHwxML4e2A09qU38u08EmQbK3Z7k",
	"I8sOwGl5SB+4c0lyC45KGztZ4YgWBfoCLfcvMj5stNRFlqGgQiEdSFqRtwRaEo+kaqPJjyiX9BuODBN4",
	"xdqVdjn7GRaFYW0WZ5q7JEaX33BldimwecHgGu1KKf/Mupp7FqEhYYqLEfExt3+uMI2FXnZ2egk7FR8G",
	"EBZ32sJRjBoXoBDn10qkoq2R393finVV/tKo5TNjws8bD7Yo5+NutnMN2R9SToenn0Ezqq7p5JoD4VhN",
	"2AqT28fuXBu5Ne4kwjVVJe2yRSVIjm8o3FDyTBFDPVnC3bd3nC5y5kIhbnwh3vL5HeTP15ytG/hXkBtr",
	"MW8h7/SMIqq5R4Om34JcQcMh0rrohVIBbNWIJpibCjl9VtMn9LKtoSHlooY8uX4l8yIqWhj74MBQjgm0",
	"xHREAagRmlBpajxfyi5gsuLajRWRGFEvOxuewA4JgfXSFg9ZAfmQi3SCN9LciN3tCf6H7iBuRAZ7E/7j",
	"288G/paKfxL2h7+Y4jjTdoD+Ts8IFWj6BUB/XWD+sI36gJfQzvSMeBDsreogt1qGXARomPz304GvDj00",
	"BnDX7BumAqBwjqWpK3ZPIhpbilQU3tfpYBC4QmGcT18NXw1DQFsFB/+82WoS8GLP+JC3m//ABNse3z7+",
	"LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
