// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type IamOtpChallenge struct {
	ID         uuid.UUID
	Phone      string
	CodeHash   []byte
	Attempts   int16
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

type IamUser struct {
	ID           uuid.UUID
	Phone        string
	Name         *string
	Locale       string
	Status       string
	PlatformRole string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
