// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOTPChallengesSince = `-- name: CountOTPChallengesSince :one
SELECT count(*)::int FROM iam.otp_challenges
WHERE phone = $1 AND created_at >= $2
`

type CountOTPChallengesSinceParams struct {
	Phone     string
	CreatedAt time.Time
}

func (q *Queries) CountOTPChallengesSince(ctx context.Context, arg CountOTPChallengesSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOTPChallengesSince, arg.Phone, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertOTPChallenge = `-- name: InsertOTPChallenge :exec

INSERT INTO iam.otp_challenges (id, phone, code_hash, attempts, created_at, expires_at, consumed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOTPChallengeParams struct {
	ID         uuid.UUID
	Phone      string
	CodeHash   []byte
	Attempts   int16
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

// Queries for the iam module. sqlc generates one Go method per query;
// the comment line names it and says what it returns (:one, :many, :exec).
func (q *Queries) InsertOTPChallenge(ctx context.Context, arg InsertOTPChallengeParams) error {
	_, err := q.db.Exec(ctx, insertOTPChallenge,
		arg.ID,
		arg.Phone,
		arg.CodeHash,
		arg.Attempts,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
	)
	return err
}

const insertUserIfNew = `-- name: InsertUserIfNew :one
INSERT INTO iam.users (id, phone, locale, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (phone) DO NOTHING
RETURNING id
`

type InsertUserIfNewParams struct {
	ID        uuid.UUID
	Phone     string
	Locale    string
	CreatedAt time.Time
}

// Registration is idempotent: a second verify for the same new number
// (retry, double tap) returns the existing user instead of failing.
func (q *Queries) InsertUserIfNew(ctx context.Context, arg InsertUserIfNewParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserIfNew,
		arg.ID,
		arg.Phone,
		arg.Locale,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const latestOTPChallenge = `-- name: LatestOTPChallenge :one
SELECT id, phone, code_hash, attempts, created_at, expires_at, consumed_at
FROM iam.otp_challenges
WHERE phone = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestOTPChallenge(ctx context.Context, phone string) (IamOtpChallenge, error) {
	row := q.db.QueryRow(ctx, latestOTPChallenge, phone)
	var i IamOtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const latestOTPChallengeForUpdate = `-- name: LatestOTPChallengeForUpdate :one
SELECT id, phone, code_hash, attempts, created_at, expires_at, consumed_at
FROM iam.otp_challenges
WHERE phone = $1
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

// Locks the row until the transaction ends, so two parallel guesses can't
// both slip past the attempt limit.
func (q *Queries) LatestOTPChallengeForUpdate(ctx context.Context, phone string) (IamOtpChallenge, error) {
	row := q.db.QueryRow(ctx, latestOTPChallengeForUpdate, phone)
	var i IamOtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const loadOTPGuard = `-- name: LoadOTPGuard :one
SELECT failures, window_start, locked_until FROM iam.otp_phone_guards WHERE phone = $1
`

type LoadOTPGuardRow struct {
	Failures    int16
	WindowStart time.Time
	LockedUntil time.Time
}

func (q *Queries) LoadOTPGuard(ctx context.Context, phone string) (LoadOTPGuardRow, error) {
	row := q.db.QueryRow(ctx, loadOTPGuard, phone)
	var i LoadOTPGuardRow
	err := row.Scan(&i.Failures, &i.WindowStart, &i.LockedUntil)
	return i, err
}

const lockOTPPhone = `-- name: LockOTPPhone :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 482193))
`

// Transaction lock also covers phones with no rows yet. Hash collisions only
// serialize unrelated phones; they cannot bypass a limit. Seed namespaces IAM.
func (q *Queries) LockOTPPhone(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockOTPPhone, dollar_1)
	return err
}

const saveOTPGuard = `-- name: SaveOTPGuard :exec
INSERT INTO iam.otp_phone_guards (phone, failures, window_start, locked_until)
VALUES ($1, $2, $3, $4)
ON CONFLICT (phone) DO UPDATE SET failures = EXCLUDED.failures,
 window_start = EXCLUDED.window_start, locked_until = EXCLUDED.locked_until
`

type SaveOTPGuardParams struct {
	Phone       string
	Failures    int16
	WindowStart time.Time
	LockedUntil time.Time
}

func (q *Queries) SaveOTPGuard(ctx context.Context, arg SaveOTPGuardParams) error {
	_, err := q.db.Exec(ctx, saveOTPGuard,
		arg.Phone,
		arg.Failures,
		arg.WindowStart,
		arg.LockedUntil,
	)
	return err
}

const updateOTPChallenge = `-- name: UpdateOTPChallenge :exec
UPDATE iam.otp_challenges
SET attempts = $2, consumed_at = $3
WHERE id = $1
`

type UpdateOTPChallengeParams struct {
	ID         uuid.UUID
	Attempts   int16
	ConsumedAt *time.Time
}

func (q *Queries) UpdateOTPChallenge(ctx context.Context, arg UpdateOTPChallengeParams) error {
	_, err := q.db.Exec(ctx, updateOTPChallenge, arg.ID, arg.Attempts, arg.ConsumedAt)
	return err
}

const userByPhone = `-- name: UserByPhone :one
SELECT id, phone, name, locale, status, platform_role, created_at, updated_at
FROM iam.users
WHERE phone = $1
`

func (q *Queries) UserByPhone(ctx context.Context, phone string) (IamUser, error) {
	row := q.db.QueryRow(ctx, userByPhone, phone)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Locale,
		&i.Status,
		&i.PlatformRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
