// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const busyIntervals = `-- name: BusyIntervals :many

SELECT staff_id, lower(during)::timestamptz AS busy_from, upper(during)::timestamptz AS busy_to
FROM booking.appointments
WHERE staff_id = ANY($1::uuid[])
  AND status IN ('pending', 'confirmed')
  AND during && tstzrange($2::timestamptz, $3::timestamptz)
ORDER BY staff_id, lower(during)
`

type BusyIntervalsParams struct {
	Staff    []uuid.UUID
	FromTime time.Time
	ToTime   time.Time
}

type BusyIntervalsRow struct {
	StaffID  uuid.UUID
	BusyFrom time.Time
	BusyTo   time.Time
}

// booking's queries. Only the booking schema is touched here.
// Active appointments of these barbers overlapping [from, to): the time
// each can't take another booking (the exclusion constraint's own index
// serves it).
func (q *Queries) BusyIntervals(ctx context.Context, arg BusyIntervalsParams) ([]BusyIntervalsRow, error) {
	rows, err := q.db.Query(ctx, busyIntervals, arg.Staff, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusyIntervalsRow{}
	for rows.Next() {
		var i BusyIntervalsRow
		if err := rows.Scan(&i.StaffID, &i.BusyFrom, &i.BusyTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
