// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const branchByID = `-- name: BranchByID :one
SELECT branch_id, version, name_ar, name_en, timezone
FROM notification.branches
WHERE branch_id = $1
`

func (q *Queries) BranchByID(ctx context.Context, branchID uuid.UUID) (NotificationBranch, error) {
	row := q.db.QueryRow(ctx, branchByID, branchID)
	var i NotificationBranch
	err := row.Scan(
		&i.BranchID,
		&i.Version,
		&i.NameAr,
		&i.NameEn,
		&i.Timezone,
	)
	return i, err
}

const delivered = `-- name: Delivered :one
SELECT EXISTS (SELECT FROM notification.deliveries WHERE event_id = $1 AND device_id = $2)
`

type DeliveredParams struct {
	EventID  uuid.UUID
	DeviceID uuid.UUID
}

func (q *Queries) Delivered(ctx context.Context, arg DeliveredParams) (bool, error) {
	row := q.db.QueryRow(ctx, delivered, arg.EventID, arg.DeviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const devicesOfUser = `-- name: DevicesOfUser :many
SELECT id, user_id, token, platform, locale, created_at, updated_at
FROM notification.devices
WHERE user_id = $1
ORDER BY updated_at DESC, id DESC
`

// A user's devices, newest first.
func (q *Queries) DevicesOfUser(ctx context.Context, userID uuid.UUID) ([]NotificationDevice, error) {
	rows, err := q.db.Query(ctx, devicesOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDevice{}
	for rows.Next() {
		var i NotificationDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forgetDevice = `-- name: ForgetDevice :exec
DELETE FROM notification.devices WHERE id = $1
`

// Drops a device the push service no longer knows, whoever's it is.
func (q *Queries) ForgetDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, forgetDevice, id)
	return err
}

const keepBranch = `-- name: KeepBranch :execrows
INSERT INTO notification.branches (branch_id, version, name_ar, name_en, timezone)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (branch_id) DO UPDATE SET
    version  = excluded.version,
    name_ar  = excluded.name_ar,
    name_en  = excluded.name_en,
    timezone = excluded.timezone
WHERE notification.branches.version < excluded.version
`

type KeepBranchParams struct {
	BranchID uuid.UUID
	Version  int32
	NameAr   string
	NameEn   string
	Timezone string
}

// Saves notification's copy of a branch, unless the copy already holds this
// version or a newer one: events can arrive twice and out of order.
func (q *Queries) KeepBranch(ctx context.Context, arg KeepBranchParams) (int64, error) {
	result, err := q.db.Exec(ctx, keepBranch,
		arg.BranchID,
		arg.Version,
		arg.NameAr,
		arg.NameEn,
		arg.Timezone,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDelivery = `-- name: RecordDelivery :exec
INSERT INTO notification.deliveries (event_id, device_id, user_id, kind, appointment_id, outcome, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (event_id, device_id) DO NOTHING
`

type RecordDeliveryParams struct {
	EventID       uuid.UUID
	DeviceID      uuid.UUID
	UserID        uuid.UUID
	Kind          string
	AppointmentID *uuid.UUID
	Outcome       string
	SentAt        time.Time
}

// Logs a push's outcome. Recorded twice (a retry), it stays one row.
func (q *Queries) RecordDelivery(ctx context.Context, arg RecordDeliveryParams) error {
	_, err := q.db.Exec(ctx, recordDelivery,
		arg.EventID,
		arg.DeviceID,
		arg.UserID,
		arg.Kind,
		arg.AppointmentID,
		arg.Outcome,
		arg.SentAt,
	)
	return err
}

const removeDevice = `-- name: RemoveDevice :execrows
DELETE FROM notification.devices WHERE id = $1 AND user_id = $2
`

type RemoveDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveDevice(ctx context.Context, arg RemoveDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeDevice, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveDevice = `-- name: SaveDevice :one

INSERT INTO notification.devices (id, user_id, token, platform, locale, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
ON CONFLICT (token) DO UPDATE SET
    id         = CASE WHEN notification.devices.user_id = excluded.user_id
                      THEN notification.devices.id ELSE excluded.id END,
    created_at = CASE WHEN notification.devices.user_id = excluded.user_id
                      THEN notification.devices.created_at ELSE excluded.created_at END,
    user_id    = excluded.user_id,
    platform   = excluded.platform,
    locale     = excluded.locale,
    updated_at = excluded.updated_at
RETURNING id, user_id, platform, locale, created_at, updated_at
`

type SaveDeviceParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Token    string
	Platform string
	Locale   string
	Now      time.Time
}

type SaveDeviceRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Platform  string
	Locale    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// notification's queries. They touch only the notification schema.
// Registers a device by its token. The same token registered again keeps
// its row and refreshes it; registered by another user (another account
// signed in on the phone), it becomes a new registration of theirs.
func (q *Queries) SaveDevice(ctx context.Context, arg SaveDeviceParams) (SaveDeviceRow, error) {
	row := q.db.QueryRow(ctx, saveDevice,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Platform,
		arg.Locale,
		arg.Now,
	)
	var i SaveDeviceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trimDevices = `-- name: TrimDevices :exec
DELETE FROM notification.devices AS old
WHERE old.user_id = $1
  AND old.id NOT IN (SELECT d.id FROM notification.devices d
                     WHERE d.user_id = $1
                     ORDER BY d.updated_at DESC, d.id DESC
                     LIMIT $2)
`

type TrimDevicesParams struct {
	UserID uuid.UUID
	Keep   int32
}

// Keeps only the user's newest devices.
func (q *Queries) TrimDevices(ctx context.Context, arg TrimDevicesParams) error {
	_, err := q.db.Exec(ctx, trimDevices, arg.UserID, arg.Keep)
	return err
}
