// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM media.objects WHERE id = $1
`

func (q *Queries) DeleteObject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteObject, id)
	return err
}

const insertObject = `-- name: InsertObject :exec

INSERT INTO media.objects (id, purpose, content_type, size_bytes, sha256, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertObjectParams struct {
	ID          uuid.UUID
	Purpose     string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

// media queries. Only the media schema, never another module's.
// Run `make generate` after editing; sqlc writes sqlcgen/.
func (q *Queries) InsertObject(ctx context.Context, arg InsertObjectParams) error {
	_, err := q.db.Exec(ctx, insertObject,
		arg.ID,
		arg.Purpose,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const objectByID = `-- name: ObjectByID :one
SELECT id, purpose, content_type, size_bytes, sha256, created_by, created_at FROM media.objects WHERE id = $1
`

func (q *Queries) ObjectByID(ctx context.Context, id uuid.UUID) (MediaObject, error) {
	row := q.db.QueryRow(ctx, objectByID, id)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
