// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type BusinessBusiness struct {
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
	DisplayNameAr string
	DisplayNameEn string
	LegalName     string
	CrNumber      string
	Status        string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BusinessStaffMember struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	UserID     *uuid.UUID
	Role       string
	Active     bool
	CreatedAt  time.Time
}

type IamOtpChallenge struct {
	ID         uuid.UUID
	Phone      string
	CodeHash   []byte
	Attempts   int16
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

type IamOtpPhoneGuard struct {
	Phone       string
	Failures    int16
	WindowStart time.Time
	LockedUntil time.Time
}

type IamRefreshToken struct {
	TokenHash []byte
	SessionID uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type IamSession struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	CreatedAt       time.Time
	LastRefreshedAt time.Time
	RevokedAt       *time.Time
	RevokeReason    *string
}

type IamUser struct {
	ID           uuid.UUID
	Phone        string
	Name         *string
	Locale       string
	Status       string
	PlatformRole string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
