// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const businessByID = `-- name: BusinessByID :one
SELECT id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at FROM business.businesses WHERE id = $1
`

func (q *Queries) BusinessByID(ctx context.Context, id uuid.UUID) (BusinessBusiness, error) {
	row := q.db.QueryRow(ctx, businessByID, id)
	var i BusinessBusiness
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayNameAr,
		&i.DisplayNameEn,
		&i.LegalName,
		&i.CrNumber,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const businessByIDForUpdate = `-- name: BusinessByIDForUpdate :one

SELECT id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at FROM business.businesses WHERE id = $1 FOR UPDATE
`

// UUIDv7: newest first
// Locks the row until the transaction ends: a second editor waits here.
func (q *Queries) BusinessByIDForUpdate(ctx context.Context, id uuid.UUID) (BusinessBusiness, error) {
	row := q.db.QueryRow(ctx, businessByIDForUpdate, id)
	var i BusinessBusiness
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayNameAr,
		&i.DisplayNameEn,
		&i.LegalName,
		&i.CrNumber,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBusiness = `-- name: InsertBusiness :exec

INSERT INTO business.businesses (id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertBusinessParams struct {
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
	DisplayNameAr string
	DisplayNameEn string
	LegalName     string
	CrNumber      string
	Status        string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// business queries. Only the business schema, never another module's.
// Run `make generate` after editing; sqlc writes sqlcgen/.
func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) error {
	_, err := q.db.Exec(ctx, insertBusiness,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayNameAr,
		arg.DisplayNameEn,
		arg.LegalName,
		arg.CrNumber,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertStaffMember = `-- name: InsertStaffMember :exec
INSERT INTO business.staff_members (id, business_id, user_id, role, active, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertStaffMemberParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	UserID     *uuid.UUID
	Role       string
	Active     bool
	CreatedAt  time.Time
}

func (q *Queries) InsertStaffMember(ctx context.Context, arg InsertStaffMemberParams) error {
	_, err := q.db.Exec(ctx, insertStaffMember,
		arg.ID,
		arg.BusinessID,
		arg.UserID,
		arg.Role,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const membershipsForUser = `-- name: MembershipsForUser :many
SELECT s.id AS staff_id, s.role, b.id AS business_id, b.display_name_ar, b.display_name_en, b.status
FROM business.staff_members s
JOIN business.businesses b ON b.id = s.business_id
WHERE s.user_id = $1 AND s.active
ORDER BY b.id DESC
`

type MembershipsForUserRow struct {
	StaffID       uuid.UUID
	Role          string
	BusinessID    uuid.UUID
	DisplayNameAr string
	DisplayNameEn string
	Status        string
}

func (q *Queries) MembershipsForUser(ctx context.Context, userID *uuid.UUID) ([]MembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, membershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipsForUserRow{}
	for rows.Next() {
		var i MembershipsForUserRow
		if err := rows.Scan(
			&i.StaffID,
			&i.Role,
			&i.BusinessID,
			&i.DisplayNameAr,
			&i.DisplayNameEn,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffMembership = `-- name: StaffMembership :one
SELECT id, business_id, user_id, role, active, created_at FROM business.staff_members WHERE business_id = $1 AND user_id = $2
`

type StaffMembershipParams struct {
	BusinessID uuid.UUID
	UserID     *uuid.UUID
}

func (q *Queries) StaffMembership(ctx context.Context, arg StaffMembershipParams) (BusinessStaffMember, error) {
	row := q.db.QueryRow(ctx, staffMembership, arg.BusinessID, arg.UserID)
	var i BusinessStaffMember
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateBusiness = `-- name: UpdateBusiness :execrows
UPDATE business.businesses
SET display_name_ar = $1, display_name_en = $2, legal_name = $3,
    status = $4, version = $5, updated_at = $6
WHERE id = $7 AND version = $8
`

type UpdateBusinessParams struct {
	DisplayNameAr   string
	DisplayNameEn   string
	LegalName       string
	Status          string
	Version         int32
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

// The version check is repeated in the WHERE clause as a second guard:
// it matches no row if the version moved since the caller read it.
func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBusiness,
		arg.DisplayNameAr,
		arg.DisplayNameEn,
		arg.LegalName,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
