// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// A transaction lock on a name, for what no row lock covers: invitations
// to one phone across businesses, one user's registrations.
func (q *Queries) AdvisoryLock(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, advisoryLock, name)
	return err
}

const branchByID = `-- name: BranchByID :one
SELECT id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status, min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm, pending_expiry_minutes, max_active_bookings, version, created_at, updated_at FROM business.branches WHERE business_id = $1 AND id = $2
`

type BranchByIDParams struct {
	BusinessID uuid.UUID
	ID         uuid.UUID
}

// Always by (business_id, id): another business's branch ID finds nothing.
func (q *Queries) BranchByID(ctx context.Context, arg BranchByIDParams) (BusinessBranch, error) {
	row := q.db.QueryRow(ctx, branchByID, arg.BusinessID, arg.ID)
	var i BusinessBranch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.NameAr,
		&i.NameEn,
		&i.CityCode,
		&i.District,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Timezone,
		&i.Status,
		&i.MinLeadMinutes,
		&i.HorizonDays,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.CancellationMinutes,
		&i.AutoConfirm,
		&i.PendingExpiryMinutes,
		&i.MaxActiveBookings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const branchByIDForUpdate = `-- name: BranchByIDForUpdate :one
SELECT id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status, min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm, pending_expiry_minutes, max_active_bookings, version, created_at, updated_at FROM business.branches WHERE business_id = $1 AND id = $2 FOR NO KEY UPDATE
`

type BranchByIDForUpdateParams struct {
	BusinessID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) BranchByIDForUpdate(ctx context.Context, arg BranchByIDForUpdateParams) (BusinessBranch, error) {
	row := q.db.QueryRow(ctx, branchByIDForUpdate, arg.BusinessID, arg.ID)
	var i BusinessBranch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.NameAr,
		&i.NameEn,
		&i.CityCode,
		&i.District,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Timezone,
		&i.Status,
		&i.MinLeadMinutes,
		&i.HorizonDays,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.CancellationMinutes,
		&i.AutoConfirm,
		&i.PendingExpiryMinutes,
		&i.MaxActiveBookings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const branchesByBusiness = `-- name: BranchesByBusiness :many
SELECT id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status, min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm, pending_expiry_minutes, max_active_bookings, version, created_at, updated_at FROM business.branches WHERE business_id = $1 ORDER BY id
`

func (q *Queries) BranchesByBusiness(ctx context.Context, businessID uuid.UUID) ([]BusinessBranch, error) {
	rows, err := q.db.Query(ctx, branchesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessBranch{}
	for rows.Next() {
		var i BusinessBranch
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.Status,
			&i.MinLeadMinutes,
			&i.HorizonDays,
			&i.SlotIntervalMinutes,
			&i.BufferMinutes,
			&i.CancellationMinutes,
			&i.AutoConfirm,
			&i.PendingExpiryMinutes,
			&i.MaxActiveBookings,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const businessByID = `-- name: BusinessByID :one
SELECT id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at, submitted_at, reviewed_at, reviewed_by, rejection_reason FROM business.businesses WHERE id = $1
`

func (q *Queries) BusinessByID(ctx context.Context, id uuid.UUID) (BusinessBusiness, error) {
	row := q.db.QueryRow(ctx, businessByID, id)
	var i BusinessBusiness
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayNameAr,
		&i.DisplayNameEn,
		&i.LegalName,
		&i.CrNumber,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
	)
	return i, err
}

const businessByIDForUpdate = `-- name: BusinessByIDForUpdate :one

SELECT id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at, submitted_at, reviewed_at, reviewed_by, rejection_reason FROM business.businesses WHERE id = $1 FOR NO KEY UPDATE
`

// UUIDv7: newest first
// Locks the row until the transaction ends: a second editor waits here.
// NO KEY: the id never changes, so rows that reference the business
// (branches, invitations) can still be inserted meanwhile.
func (q *Queries) BusinessByIDForUpdate(ctx context.Context, id uuid.UUID) (BusinessBusiness, error) {
	row := q.db.QueryRow(ctx, businessByIDForUpdate, id)
	var i BusinessBusiness
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayNameAr,
		&i.DisplayNameEn,
		&i.LegalName,
		&i.CrNumber,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
	)
	return i, err
}

const businessesForReview = `-- name: BusinessesForReview :many
SELECT id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at, submitted_at, reviewed_at, reviewed_by, rejection_reason FROM business.businesses
WHERE status = $1
  AND ($2::timestamptz IS NULL
       OR (submitted_at, id) > ($2::timestamptz, $3::uuid))
ORDER BY submitted_at, id
LIMIT $4
`

type BusinessesForReviewParams struct {
	Status           string
	AfterSubmittedAt *time.Time
	AfterID          *uuid.UUID
	PageSize         int32
}

// One page of the admin queue: one status, oldest submission first. The
// cursor is the (submitted_at, id) of the last row of the previous page.
func (q *Queries) BusinessesForReview(ctx context.Context, arg BusinessesForReviewParams) ([]BusinessBusiness, error) {
	rows, err := q.db.Query(ctx, businessesForReview,
		arg.Status,
		arg.AfterSubmittedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessBusiness{}
	for rows.Next() {
		var i BusinessBusiness
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.DisplayNameAr,
			&i.DisplayNameEn,
			&i.LegalName,
			&i.CrNumber,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.RejectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBranches = `-- name: CountBranches :one
SELECT count(*) FROM business.branches WHERE business_id = $1
`

func (q *Queries) CountBranches(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBranches, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBranchesIn = `-- name: CountBranchesIn :one
SELECT count(*) FROM business.branches WHERE business_id = $1 AND id = ANY($2::uuid[])
`

type CountBranchesInParams struct {
	BusinessID uuid.UUID
	Ids        []uuid.UUID
}

func (q *Queries) CountBranchesIn(ctx context.Context, arg CountBranchesInParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBranchesIn, arg.BusinessID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenRegistrations = `-- name: CountOpenRegistrations :one
SELECT count(*) FROM business.businesses
WHERE owner_user_id = $1 AND status IN ('draft', 'pending_review', 'rejected')
`

func (q *Queries) CountOpenRegistrations(ctx context.Context, ownerUserID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenRegistrations, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaffSeats = `-- name: CountStaffSeats :one
SELECT ((SELECT count(*) FROM business.staff_members s
          WHERE s.business_id = $1 AND s.role <> 'owner' AND s.active)
      + (SELECT count(*) FROM business.invitations i
          WHERE i.business_id = $1 AND i.status = 'pending' AND i.expires_at > $2::timestamptz))::int AS seats
`

type CountStaffSeatsParams struct {
	BusinessID uuid.UUID
	Now        time.Time
}

// Seats in use: active managers and barbers, plus invitations that can
// still be accepted. The owner doesn't take a seat.
func (q *Queries) CountStaffSeats(ctx context.Context, arg CountStaffSeatsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countStaffSeats, arg.BusinessID, arg.Now)
	var seats int32
	err := row.Scan(&seats)
	return seats, err
}

const countVerificationDocuments = `-- name: CountVerificationDocuments :one
SELECT count(*) FROM business.verification_documents WHERE business_id = $1
`

func (q *Queries) CountVerificationDocuments(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVerificationDocuments, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBranch = `-- name: InsertBranch :exec
INSERT INTO business.branches (
    id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status,
    min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm,
    pending_expiry_minutes, max_active_bookings, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23
)
`

type InsertBranchParams struct {
	ID                   uuid.UUID
	BusinessID           uuid.UUID
	NameAr               string
	NameEn               string
	CityCode             string
	District             string
	Address              string
	Latitude             float64
	Longitude            float64
	Phone                *string
	Timezone             string
	Status               string
	MinLeadMinutes       int32
	HorizonDays          int16
	SlotIntervalMinutes  int16
	BufferMinutes        int16
	CancellationMinutes  int32
	AutoConfirm          bool
	PendingExpiryMinutes int16
	MaxActiveBookings    int16
	Version              int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) InsertBranch(ctx context.Context, arg InsertBranchParams) error {
	_, err := q.db.Exec(ctx, insertBranch,
		arg.ID,
		arg.BusinessID,
		arg.NameAr,
		arg.NameEn,
		arg.CityCode,
		arg.District,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Timezone,
		arg.Status,
		arg.MinLeadMinutes,
		arg.HorizonDays,
		arg.SlotIntervalMinutes,
		arg.BufferMinutes,
		arg.CancellationMinutes,
		arg.AutoConfirm,
		arg.PendingExpiryMinutes,
		arg.MaxActiveBookings,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertBusiness = `-- name: InsertBusiness :exec

INSERT INTO business.businesses (id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertBusinessParams struct {
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
	DisplayNameAr string
	DisplayNameEn string
	LegalName     string
	CrNumber      string
	Status        string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// business queries. Only the business schema, never another module's.
// Run `make generate` after editing; sqlc writes sqlcgen/.
func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) error {
	_, err := q.db.Exec(ctx, insertBusiness,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayNameAr,
		arg.DisplayNameEn,
		arg.LegalName,
		arg.CrNumber,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertInvitation = `-- name: InsertInvitation :exec
INSERT INTO business.invitations (id, business_id, phone, display_name, role, branch_ids, token_hash, status, invited_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertInvitationParams struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	Phone       string
	DisplayName string
	Role        string
	BranchIds   []uuid.UUID
	TokenHash   []byte
	Status      string
	InvitedBy   uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) error {
	_, err := q.db.Exec(ctx, insertInvitation,
		arg.ID,
		arg.BusinessID,
		arg.Phone,
		arg.DisplayName,
		arg.Role,
		arg.BranchIds,
		arg.TokenHash,
		arg.Status,
		arg.InvitedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertStaffBranch = `-- name: InsertStaffBranch :exec
INSERT INTO business.staff_branches (staff_id, branch_id, business_id) VALUES ($1, $2, $3)
`

type InsertStaffBranchParams struct {
	StaffID    uuid.UUID
	BranchID   uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) InsertStaffBranch(ctx context.Context, arg InsertStaffBranchParams) error {
	_, err := q.db.Exec(ctx, insertStaffBranch, arg.StaffID, arg.BranchID, arg.BusinessID)
	return err
}

const insertStaffMember = `-- name: InsertStaffMember :exec
INSERT INTO business.staff_members (id, business_id, user_id, role, active, created_at, display_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertStaffMemberParams struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	UserID      *uuid.UUID
	Role        string
	Active      bool
	CreatedAt   time.Time
	DisplayName string
}

func (q *Queries) InsertStaffMember(ctx context.Context, arg InsertStaffMemberParams) error {
	_, err := q.db.Exec(ctx, insertStaffMember,
		arg.ID,
		arg.BusinessID,
		arg.UserID,
		arg.Role,
		arg.Active,
		arg.CreatedAt,
		arg.DisplayName,
	)
	return err
}

const insertVerificationDocument = `-- name: InsertVerificationDocument :exec
INSERT INTO business.verification_documents (object_id, business_id, kind, content_type, size_bytes, uploaded_by, uploaded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertVerificationDocumentParams struct {
	ObjectID    uuid.UUID
	BusinessID  uuid.UUID
	Kind        string
	ContentType string
	SizeBytes   int64
	UploadedBy  uuid.UUID
	UploadedAt  time.Time
}

func (q *Queries) InsertVerificationDocument(ctx context.Context, arg InsertVerificationDocumentParams) error {
	_, err := q.db.Exec(ctx, insertVerificationDocument,
		arg.ObjectID,
		arg.BusinessID,
		arg.Kind,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
		arg.UploadedAt,
	)
	return err
}

const invitationByTokenForUpdate = `-- name: InvitationByTokenForUpdate :one
SELECT id, business_id, phone, display_name, role, branch_ids, token_hash, status, invited_by, created_at, expires_at, accepted_at, accepted_by FROM business.invitations WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) InvitationByTokenForUpdate(ctx context.Context, tokenHash []byte) (BusinessInvitation, error) {
	row := q.db.QueryRow(ctx, invitationByTokenForUpdate, tokenHash)
	var i BusinessInvitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Phone,
		&i.DisplayName,
		&i.Role,
		&i.BranchIds,
		&i.TokenHash,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
	)
	return i, err
}

const invitationForUpdate = `-- name: InvitationForUpdate :one
SELECT id, business_id, phone, display_name, role, branch_ids, token_hash, status, invited_by, created_at, expires_at, accepted_at, accepted_by FROM business.invitations WHERE business_id = $1 AND id = $2 FOR UPDATE
`

type InvitationForUpdateParams struct {
	BusinessID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) InvitationForUpdate(ctx context.Context, arg InvitationForUpdateParams) (BusinessInvitation, error) {
	row := q.db.QueryRow(ctx, invitationForUpdate, arg.BusinessID, arg.ID)
	var i BusinessInvitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Phone,
		&i.DisplayName,
		&i.Role,
		&i.BranchIds,
		&i.TokenHash,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
	)
	return i, err
}

const inviteHistory = `-- name: InviteHistory :one
SELECT
    (SELECT coalesce(max(i.created_at), $1::timestamptz) FROM business.invitations i
     WHERE i.business_id = $2 AND i.phone = $3 AND i.created_at > $1)::timestamptz AS last_to_phone,
    (SELECT count(*) FROM business.invitations i
     WHERE i.phone = $3 AND i.created_at > $1) AS to_phone,
    (SELECT coalesce(min(i.created_at), $1::timestamptz) FROM business.invitations i
     WHERE i.phone = $3 AND i.created_at > $1)::timestamptz AS oldest_to_phone,
    (SELECT count(*) FROM business.invitations i
     WHERE i.business_id = $2 AND i.created_at > $1) AS by_business,
    (SELECT coalesce(min(i.created_at), $1::timestamptz) FROM business.invitations i
     WHERE i.business_id = $2 AND i.created_at > $1)::timestamptz AS oldest_by_business
`

type InviteHistoryParams struct {
	Since      time.Time
	BusinessID uuid.UUID
	Phone      string
}

type InviteHistoryRow struct {
	LastToPhone      time.Time
	ToPhone          int64
	OldestToPhone    time.Time
	ByBusiness       int64
	OldestByBusiness time.Time
}

// What the invitation limits need, in one round trip (both indexes above).
func (q *Queries) InviteHistory(ctx context.Context, arg InviteHistoryParams) (InviteHistoryRow, error) {
	row := q.db.QueryRow(ctx, inviteHistory, arg.Since, arg.BusinessID, arg.Phone)
	var i InviteHistoryRow
	err := row.Scan(
		&i.LastToPhone,
		&i.ToPhone,
		&i.OldestToPhone,
		&i.ByBusiness,
		&i.OldestByBusiness,
	)
	return i, err
}

const lockBusiness = `-- name: LockBusiness :one
SELECT id FROM business.businesses WHERE id = $1 FOR NO KEY UPDATE
`

// Takes turns between additions to one business (invitations, branches), so
// two at once can't both pass a count check. NO KEY UPDATE doesn't block
// rows that merely reference the business (their foreign-key checks).
func (q *Queries) LockBusiness(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockBusiness, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const membershipsForUser = `-- name: MembershipsForUser :many
SELECT s.id AS staff_id, s.role, b.id AS business_id, b.display_name_ar, b.display_name_en, b.status
FROM business.staff_members s
JOIN business.businesses b ON b.id = s.business_id
WHERE s.user_id = $1 AND s.active
ORDER BY b.id DESC
`

type MembershipsForUserRow struct {
	StaffID       uuid.UUID
	Role          string
	BusinessID    uuid.UUID
	DisplayNameAr string
	DisplayNameEn string
	Status        string
}

func (q *Queries) MembershipsForUser(ctx context.Context, userID *uuid.UUID) ([]MembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, membershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipsForUserRow{}
	for rows.Next() {
		var i MembershipsForUserRow
		if err := rows.Scan(
			&i.StaffID,
			&i.Role,
			&i.BusinessID,
			&i.DisplayNameAr,
			&i.DisplayNameEn,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingInvitations = `-- name: PendingInvitations :many
SELECT id, business_id, phone, display_name, role, branch_ids, token_hash, status, invited_by, created_at, expires_at, accepted_at, accepted_by FROM business.invitations WHERE business_id = $1 AND status = 'pending' ORDER BY created_at DESC, id
`

func (q *Queries) PendingInvitations(ctx context.Context, businessID uuid.UUID) ([]BusinessInvitation, error) {
	rows, err := q.db.Query(ctx, pendingInvitations, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessInvitation{}
	for rows.Next() {
		var i BusinessInvitation
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Phone,
			&i.DisplayName,
			&i.Role,
			&i.BranchIds,
			&i.TokenHash,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePendingInvitations = `-- name: RevokePendingInvitations :exec
UPDATE business.invitations SET status = 'revoked'
WHERE business_id = $1 AND phone = $2 AND status = 'pending'
`

type RevokePendingInvitationsParams struct {
	BusinessID uuid.UUID
	Phone      string
}

func (q *Queries) RevokePendingInvitations(ctx context.Context, arg RevokePendingInvitationsParams) error {
	_, err := q.db.Exec(ctx, revokePendingInvitations, arg.BusinessID, arg.Phone)
	return err
}

const saveInvitation = `-- name: SaveInvitation :exec
UPDATE business.invitations SET status = $1, accepted_at = $2, accepted_by = $3
WHERE id = $4
`

type SaveInvitationParams struct {
	Status     string
	AcceptedAt *time.Time
	AcceptedBy *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) SaveInvitation(ctx context.Context, arg SaveInvitationParams) error {
	_, err := q.db.Exec(ctx, saveInvitation,
		arg.Status,
		arg.AcceptedAt,
		arg.AcceptedBy,
		arg.ID,
	)
	return err
}

const staffByBusiness = `-- name: StaffByBusiness :many
SELECT s.id, s.business_id, s.user_id, s.role, s.active, s.created_at, s.display_name,
       coalesce(array_agg(sb.branch_id) FILTER (WHERE sb.branch_id IS NOT NULL), '{}')::uuid[] AS branch_ids
FROM business.staff_members s
LEFT JOIN business.staff_branches sb ON sb.staff_id = s.id
WHERE s.business_id = $1
GROUP BY s.id
ORDER BY s.created_at, s.id
`

type StaffByBusinessRow struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	UserID      *uuid.UUID
	Role        string
	Active      bool
	CreatedAt   time.Time
	DisplayName string
	BranchIds   []uuid.UUID
}

func (q *Queries) StaffByBusiness(ctx context.Context, businessID uuid.UUID) ([]StaffByBusinessRow, error) {
	rows, err := q.db.Query(ctx, staffByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffByBusinessRow{}
	for rows.Next() {
		var i StaffByBusinessRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.UserID,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.DisplayName,
			&i.BranchIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffMembership = `-- name: StaffMembership :one
SELECT s.id, s.business_id, s.user_id, s.role, s.active, s.created_at, s.display_name,
       coalesce(array_agg(sb.branch_id) FILTER (WHERE sb.branch_id IS NOT NULL), '{}')::uuid[] AS branch_ids
FROM business.staff_members s
LEFT JOIN business.staff_branches sb ON sb.staff_id = s.id
WHERE s.business_id = $1 AND s.user_id = $2
GROUP BY s.id
`

type StaffMembershipParams struct {
	BusinessID uuid.UUID
	UserID     *uuid.UUID
}

type StaffMembershipRow struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	UserID      *uuid.UUID
	Role        string
	Active      bool
	CreatedAt   time.Time
	DisplayName string
	BranchIds   []uuid.UUID
}

// The caller's staff record with the branches they work at: the first query
// of every business-mode request.
func (q *Queries) StaffMembership(ctx context.Context, arg StaffMembershipParams) (StaffMembershipRow, error) {
	row := q.db.QueryRow(ctx, staffMembership, arg.BusinessID, arg.UserID)
	var i StaffMembershipRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.DisplayName,
		&i.BranchIds,
	)
	return i, err
}

const updateBranch = `-- name: UpdateBranch :execrows

UPDATE business.branches
SET name_ar = $1, name_en = $2, city_code = $3, district = $4, address = $5,
    latitude = $6, longitude = $7, phone = $8, timezone = $9, status = $10,
    min_lead_minutes = $11, horizon_days = $12, slot_interval_minutes = $13,
    buffer_minutes = $14, cancellation_minutes = $15, auto_confirm = $16,
    pending_expiry_minutes = $17, max_active_bookings = $18,
    version = $19, updated_at = $20
WHERE business_id = $21 AND id = $22 AND version = $23
`

type UpdateBranchParams struct {
	NameAr               string
	NameEn               string
	CityCode             string
	District             string
	Address              string
	Latitude             float64
	Longitude            float64
	Phone                *string
	Timezone             string
	Status               string
	MinLeadMinutes       int32
	HorizonDays          int16
	SlotIntervalMinutes  int16
	BufferMinutes        int16
	CancellationMinutes  int32
	AutoConfirm          bool
	PendingExpiryMinutes int16
	MaxActiveBookings    int16
	Version              int32
	UpdatedAt            time.Time
	BusinessID           uuid.UUID
	ID                   uuid.UUID
	ExpectedVersion      int32
}

// UUIDv7: oldest first
func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBranch,
		arg.NameAr,
		arg.NameEn,
		arg.CityCode,
		arg.District,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Timezone,
		arg.Status,
		arg.MinLeadMinutes,
		arg.HorizonDays,
		arg.SlotIntervalMinutes,
		arg.BufferMinutes,
		arg.CancellationMinutes,
		arg.AutoConfirm,
		arg.PendingExpiryMinutes,
		arg.MaxActiveBookings,
		arg.Version,
		arg.UpdatedAt,
		arg.BusinessID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBusiness = `-- name: UpdateBusiness :execrows
UPDATE business.businesses
SET display_name_ar = $1, display_name_en = $2, legal_name = $3,
    status = $4, version = $5, updated_at = $6,
    submitted_at = $7, reviewed_at = $8, reviewed_by = $9,
    rejection_reason = $10
WHERE id = $11 AND version = $12
`

type UpdateBusinessParams struct {
	DisplayNameAr   string
	DisplayNameEn   string
	LegalName       string
	Status          string
	Version         int32
	UpdatedAt       time.Time
	SubmittedAt     *time.Time
	ReviewedAt      *time.Time
	ReviewedBy      *uuid.UUID
	RejectionReason string
	ID              uuid.UUID
	ExpectedVersion int32
}

// The version check is repeated in the WHERE clause as a second guard:
// it matches no row if the version moved since the caller read it.
func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBusiness,
		arg.DisplayNameAr,
		arg.DisplayNameEn,
		arg.LegalName,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.SubmittedAt,
		arg.ReviewedAt,
		arg.ReviewedBy,
		arg.RejectionReason,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const verificationDocumentsByBusiness = `-- name: VerificationDocumentsByBusiness :many
SELECT object_id, business_id, kind, content_type, size_bytes, uploaded_by, uploaded_at FROM business.verification_documents WHERE business_id = $1 ORDER BY uploaded_at, object_id
`

func (q *Queries) VerificationDocumentsByBusiness(ctx context.Context, businessID uuid.UUID) ([]BusinessVerificationDocument, error) {
	rows, err := q.db.Query(ctx, verificationDocumentsByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessVerificationDocument{}
	for rows.Next() {
		var i BusinessVerificationDocument
		if err := rows.Scan(
			&i.ObjectID,
			&i.BusinessID,
			&i.Kind,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
