// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const branchByID = `-- name: BranchByID :one
SELECT id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status, min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm, pending_expiry_minutes, max_active_bookings, version, created_at, updated_at FROM business.branches WHERE business_id = $1 AND id = $2
`

type BranchByIDParams struct {
	BusinessID uuid.UUID
	ID         uuid.UUID
}

// Always by (business_id, id): another business's branch ID finds nothing.
func (q *Queries) BranchByID(ctx context.Context, arg BranchByIDParams) (BusinessBranch, error) {
	row := q.db.QueryRow(ctx, branchByID, arg.BusinessID, arg.ID)
	var i BusinessBranch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.NameAr,
		&i.NameEn,
		&i.CityCode,
		&i.District,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Timezone,
		&i.Status,
		&i.MinLeadMinutes,
		&i.HorizonDays,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.CancellationMinutes,
		&i.AutoConfirm,
		&i.PendingExpiryMinutes,
		&i.MaxActiveBookings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const branchByIDForUpdate = `-- name: BranchByIDForUpdate :one
SELECT id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status, min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm, pending_expiry_minutes, max_active_bookings, version, created_at, updated_at FROM business.branches WHERE business_id = $1 AND id = $2 FOR UPDATE
`

type BranchByIDForUpdateParams struct {
	BusinessID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) BranchByIDForUpdate(ctx context.Context, arg BranchByIDForUpdateParams) (BusinessBranch, error) {
	row := q.db.QueryRow(ctx, branchByIDForUpdate, arg.BusinessID, arg.ID)
	var i BusinessBranch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.NameAr,
		&i.NameEn,
		&i.CityCode,
		&i.District,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Timezone,
		&i.Status,
		&i.MinLeadMinutes,
		&i.HorizonDays,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.CancellationMinutes,
		&i.AutoConfirm,
		&i.PendingExpiryMinutes,
		&i.MaxActiveBookings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const branchesByBusiness = `-- name: BranchesByBusiness :many
SELECT id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status, min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm, pending_expiry_minutes, max_active_bookings, version, created_at, updated_at FROM business.branches WHERE business_id = $1 ORDER BY id
`

func (q *Queries) BranchesByBusiness(ctx context.Context, businessID uuid.UUID) ([]BusinessBranch, error) {
	rows, err := q.db.Query(ctx, branchesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessBranch{}
	for rows.Next() {
		var i BusinessBranch
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.NameAr,
			&i.NameEn,
			&i.CityCode,
			&i.District,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Timezone,
			&i.Status,
			&i.MinLeadMinutes,
			&i.HorizonDays,
			&i.SlotIntervalMinutes,
			&i.BufferMinutes,
			&i.CancellationMinutes,
			&i.AutoConfirm,
			&i.PendingExpiryMinutes,
			&i.MaxActiveBookings,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const businessByID = `-- name: BusinessByID :one
SELECT id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at FROM business.businesses WHERE id = $1
`

func (q *Queries) BusinessByID(ctx context.Context, id uuid.UUID) (BusinessBusiness, error) {
	row := q.db.QueryRow(ctx, businessByID, id)
	var i BusinessBusiness
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayNameAr,
		&i.DisplayNameEn,
		&i.LegalName,
		&i.CrNumber,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const businessByIDForUpdate = `-- name: BusinessByIDForUpdate :one

SELECT id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at FROM business.businesses WHERE id = $1 FOR UPDATE
`

// UUIDv7: newest first
// Locks the row until the transaction ends: a second editor waits here.
func (q *Queries) BusinessByIDForUpdate(ctx context.Context, id uuid.UUID) (BusinessBusiness, error) {
	row := q.db.QueryRow(ctx, businessByIDForUpdate, id)
	var i BusinessBusiness
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DisplayNameAr,
		&i.DisplayNameEn,
		&i.LegalName,
		&i.CrNumber,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countVerificationDocuments = `-- name: CountVerificationDocuments :one
SELECT count(*) FROM business.verification_documents WHERE business_id = $1
`

func (q *Queries) CountVerificationDocuments(ctx context.Context, businessID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVerificationDocuments, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBranch = `-- name: InsertBranch :exec
INSERT INTO business.branches (
    id, business_id, name_ar, name_en, city_code, district, address, latitude, longitude, phone, timezone, status,
    min_lead_minutes, horizon_days, slot_interval_minutes, buffer_minutes, cancellation_minutes, auto_confirm,
    pending_expiry_minutes, max_active_bookings, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23
)
`

type InsertBranchParams struct {
	ID                   uuid.UUID
	BusinessID           uuid.UUID
	NameAr               string
	NameEn               string
	CityCode             string
	District             string
	Address              string
	Latitude             float64
	Longitude            float64
	Phone                *string
	Timezone             string
	Status               string
	MinLeadMinutes       int32
	HorizonDays          int16
	SlotIntervalMinutes  int16
	BufferMinutes        int16
	CancellationMinutes  int32
	AutoConfirm          bool
	PendingExpiryMinutes int16
	MaxActiveBookings    int16
	Version              int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) InsertBranch(ctx context.Context, arg InsertBranchParams) error {
	_, err := q.db.Exec(ctx, insertBranch,
		arg.ID,
		arg.BusinessID,
		arg.NameAr,
		arg.NameEn,
		arg.CityCode,
		arg.District,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Timezone,
		arg.Status,
		arg.MinLeadMinutes,
		arg.HorizonDays,
		arg.SlotIntervalMinutes,
		arg.BufferMinutes,
		arg.CancellationMinutes,
		arg.AutoConfirm,
		arg.PendingExpiryMinutes,
		arg.MaxActiveBookings,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertBusiness = `-- name: InsertBusiness :exec

INSERT INTO business.businesses (id, owner_user_id, display_name_ar, display_name_en, legal_name, cr_number, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertBusinessParams struct {
	ID            uuid.UUID
	OwnerUserID   uuid.UUID
	DisplayNameAr string
	DisplayNameEn string
	LegalName     string
	CrNumber      string
	Status        string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// business queries. Only the business schema, never another module's.
// Run `make generate` after editing; sqlc writes sqlcgen/.
func (q *Queries) InsertBusiness(ctx context.Context, arg InsertBusinessParams) error {
	_, err := q.db.Exec(ctx, insertBusiness,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayNameAr,
		arg.DisplayNameEn,
		arg.LegalName,
		arg.CrNumber,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertStaffMember = `-- name: InsertStaffMember :exec
INSERT INTO business.staff_members (id, business_id, user_id, role, active, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertStaffMemberParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	UserID     *uuid.UUID
	Role       string
	Active     bool
	CreatedAt  time.Time
}

func (q *Queries) InsertStaffMember(ctx context.Context, arg InsertStaffMemberParams) error {
	_, err := q.db.Exec(ctx, insertStaffMember,
		arg.ID,
		arg.BusinessID,
		arg.UserID,
		arg.Role,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const insertVerificationDocument = `-- name: InsertVerificationDocument :exec
INSERT INTO business.verification_documents (object_id, business_id, kind, content_type, size_bytes, uploaded_by, uploaded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertVerificationDocumentParams struct {
	ObjectID    uuid.UUID
	BusinessID  uuid.UUID
	Kind        string
	ContentType string
	SizeBytes   int64
	UploadedBy  uuid.UUID
	UploadedAt  time.Time
}

func (q *Queries) InsertVerificationDocument(ctx context.Context, arg InsertVerificationDocumentParams) error {
	_, err := q.db.Exec(ctx, insertVerificationDocument,
		arg.ObjectID,
		arg.BusinessID,
		arg.Kind,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
		arg.UploadedAt,
	)
	return err
}

const membershipsForUser = `-- name: MembershipsForUser :many
SELECT s.id AS staff_id, s.role, b.id AS business_id, b.display_name_ar, b.display_name_en, b.status
FROM business.staff_members s
JOIN business.businesses b ON b.id = s.business_id
WHERE s.user_id = $1 AND s.active
ORDER BY b.id DESC
`

type MembershipsForUserRow struct {
	StaffID       uuid.UUID
	Role          string
	BusinessID    uuid.UUID
	DisplayNameAr string
	DisplayNameEn string
	Status        string
}

func (q *Queries) MembershipsForUser(ctx context.Context, userID *uuid.UUID) ([]MembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, membershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipsForUserRow{}
	for rows.Next() {
		var i MembershipsForUserRow
		if err := rows.Scan(
			&i.StaffID,
			&i.Role,
			&i.BusinessID,
			&i.DisplayNameAr,
			&i.DisplayNameEn,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffMembership = `-- name: StaffMembership :one
SELECT id, business_id, user_id, role, active, created_at FROM business.staff_members WHERE business_id = $1 AND user_id = $2
`

type StaffMembershipParams struct {
	BusinessID uuid.UUID
	UserID     *uuid.UUID
}

func (q *Queries) StaffMembership(ctx context.Context, arg StaffMembershipParams) (BusinessStaffMember, error) {
	row := q.db.QueryRow(ctx, staffMembership, arg.BusinessID, arg.UserID)
	var i BusinessStaffMember
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateBranch = `-- name: UpdateBranch :execrows

UPDATE business.branches
SET name_ar = $1, name_en = $2, city_code = $3, district = $4, address = $5,
    latitude = $6, longitude = $7, phone = $8, timezone = $9, status = $10,
    min_lead_minutes = $11, horizon_days = $12, slot_interval_minutes = $13,
    buffer_minutes = $14, cancellation_minutes = $15, auto_confirm = $16,
    pending_expiry_minutes = $17, max_active_bookings = $18,
    version = $19, updated_at = $20
WHERE business_id = $21 AND id = $22 AND version = $23
`

type UpdateBranchParams struct {
	NameAr               string
	NameEn               string
	CityCode             string
	District             string
	Address              string
	Latitude             float64
	Longitude            float64
	Phone                *string
	Timezone             string
	Status               string
	MinLeadMinutes       int32
	HorizonDays          int16
	SlotIntervalMinutes  int16
	BufferMinutes        int16
	CancellationMinutes  int32
	AutoConfirm          bool
	PendingExpiryMinutes int16
	MaxActiveBookings    int16
	Version              int32
	UpdatedAt            time.Time
	BusinessID           uuid.UUID
	ID                   uuid.UUID
	ExpectedVersion      int32
}

// UUIDv7: oldest first
func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBranch,
		arg.NameAr,
		arg.NameEn,
		arg.CityCode,
		arg.District,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Timezone,
		arg.Status,
		arg.MinLeadMinutes,
		arg.HorizonDays,
		arg.SlotIntervalMinutes,
		arg.BufferMinutes,
		arg.CancellationMinutes,
		arg.AutoConfirm,
		arg.PendingExpiryMinutes,
		arg.MaxActiveBookings,
		arg.Version,
		arg.UpdatedAt,
		arg.BusinessID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBusiness = `-- name: UpdateBusiness :execrows
UPDATE business.businesses
SET display_name_ar = $1, display_name_en = $2, legal_name = $3,
    status = $4, version = $5, updated_at = $6
WHERE id = $7 AND version = $8
`

type UpdateBusinessParams struct {
	DisplayNameAr   string
	DisplayNameEn   string
	LegalName       string
	Status          string
	Version         int32
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

// The version check is repeated in the WHERE clause as a second guard:
// it matches no row if the version moved since the caller read it.
func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBusiness,
		arg.DisplayNameAr,
		arg.DisplayNameEn,
		arg.LegalName,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const verificationDocumentsByBusiness = `-- name: VerificationDocumentsByBusiness :many
SELECT object_id, business_id, kind, content_type, size_bytes, uploaded_by, uploaded_at FROM business.verification_documents WHERE business_id = $1 ORDER BY uploaded_at, object_id
`

func (q *Queries) VerificationDocumentsByBusiness(ctx context.Context, businessID uuid.UUID) ([]BusinessVerificationDocument, error) {
	rows, err := q.db.Query(ctx, verificationDocumentsByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessVerificationDocument{}
	for rows.Next() {
		var i BusinessVerificationDocument
		if err := rows.Scan(
			&i.ObjectID,
			&i.BusinessID,
			&i.Kind,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
