// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOfferings = `-- name: DeleteOfferings :exec
DELETE FROM catalog.service_offerings WHERE business_id = $1 AND service_id = $2
`

type DeleteOfferingsParams struct {
	BusinessID uuid.UUID
	ServiceID  uuid.UUID
}

func (q *Queries) DeleteOfferings(ctx context.Context, arg DeleteOfferingsParams) error {
	_, err := q.db.Exec(ctx, deleteOfferings, arg.BusinessID, arg.ServiceID)
	return err
}

const insertOffering = `-- name: InsertOffering :exec
INSERT INTO catalog.service_offerings (business_id, service_id, staff_id, price_amount, price_currency, duration_minutes)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOfferingParams struct {
	BusinessID      uuid.UUID
	ServiceID       uuid.UUID
	StaffID         uuid.UUID
	PriceAmount     pgtype.Int8
	PriceCurrency   pgtype.Text
	DurationMinutes pgtype.Int2
}

func (q *Queries) InsertOffering(ctx context.Context, arg InsertOfferingParams) error {
	_, err := q.db.Exec(ctx, insertOffering,
		arg.BusinessID,
		arg.ServiceID,
		arg.StaffID,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.DurationMinutes,
	)
	return err
}

const insertService = `-- name: InsertService :exec

INSERT INTO catalog.services (
    id, business_id, branch_id, category_code, name_ar, name_en, description_ar, description_en,
    duration_minutes, price_amount, price_currency, active, sort_order, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16
)
`

type InsertServiceParams struct {
	ID              uuid.UUID
	BusinessID      uuid.UUID
	BranchID        uuid.UUID
	CategoryCode    string
	NameAr          string
	NameEn          string
	DescriptionAr   string
	DescriptionEn   string
	DurationMinutes int16
	PriceAmount     int64
	PriceCurrency   string
	Active          bool
	SortOrder       int16
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// catalog's queries. Only the catalog schema is touched here, and every
// query is scoped by business and branch.
func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) error {
	_, err := q.db.Exec(ctx, insertService,
		arg.ID,
		arg.BusinessID,
		arg.BranchID,
		arg.CategoryCode,
		arg.NameAr,
		arg.NameEn,
		arg.DescriptionAr,
		arg.DescriptionEn,
		arg.DurationMinutes,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Active,
		arg.SortOrder,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const offeringsByBranch = `-- name: OfferingsByBranch :many
SELECT o.business_id, o.service_id, o.staff_id, o.price_amount, o.price_currency, o.duration_minutes FROM catalog.service_offerings o
JOIN catalog.services s ON s.business_id = o.business_id AND s.id = o.service_id
WHERE s.business_id = $1 AND s.branch_id = $2
ORDER BY o.service_id, o.staff_id
`

type OfferingsByBranchParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
}

func (q *Queries) OfferingsByBranch(ctx context.Context, arg OfferingsByBranchParams) ([]CatalogServiceOffering, error) {
	rows, err := q.db.Query(ctx, offeringsByBranch, arg.BusinessID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogServiceOffering{}
	for rows.Next() {
		var i CatalogServiceOffering
		if err := rows.Scan(
			&i.BusinessID,
			&i.ServiceID,
			&i.StaffID,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offeringsByService = `-- name: OfferingsByService :many
SELECT business_id, service_id, staff_id, price_amount, price_currency, duration_minutes FROM catalog.service_offerings
WHERE business_id = $1 AND service_id = $2
ORDER BY staff_id
`

type OfferingsByServiceParams struct {
	BusinessID uuid.UUID
	ServiceID  uuid.UUID
}

func (q *Queries) OfferingsByService(ctx context.Context, arg OfferingsByServiceParams) ([]CatalogServiceOffering, error) {
	rows, err := q.db.Query(ctx, offeringsByService, arg.BusinessID, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogServiceOffering{}
	for rows.Next() {
		var i CatalogServiceOffering
		if err := rows.Scan(
			&i.BusinessID,
			&i.ServiceID,
			&i.StaffID,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceForUpdate = `-- name: ServiceForUpdate :one
SELECT id, business_id, branch_id, category_code, name_ar, name_en, description_ar, description_en, duration_minutes, price_amount, price_currency, active, sort_order, version, created_at, updated_at FROM catalog.services
WHERE business_id = $1 AND branch_id = $2 AND id = $3
FOR UPDATE
`

type ServiceForUpdateParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) ServiceForUpdate(ctx context.Context, arg ServiceForUpdateParams) (CatalogService, error) {
	row := q.db.QueryRow(ctx, serviceForUpdate, arg.BusinessID, arg.BranchID, arg.ID)
	var i CatalogService
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BranchID,
		&i.CategoryCode,
		&i.NameAr,
		&i.NameEn,
		&i.DescriptionAr,
		&i.DescriptionEn,
		&i.DurationMinutes,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.Active,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const servicesByBranch = `-- name: ServicesByBranch :many
SELECT id, business_id, branch_id, category_code, name_ar, name_en, description_ar, description_en, duration_minutes, price_amount, price_currency, active, sort_order, version, created_at, updated_at FROM catalog.services
WHERE business_id = $1 AND branch_id = $2
ORDER BY sort_order, created_at, id
`

type ServicesByBranchParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
}

func (q *Queries) ServicesByBranch(ctx context.Context, arg ServicesByBranchParams) ([]CatalogService, error) {
	rows, err := q.db.Query(ctx, servicesByBranch, arg.BusinessID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogService{}
	for rows.Next() {
		var i CatalogService
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BranchID,
			&i.CategoryCode,
			&i.NameAr,
			&i.NameEn,
			&i.DescriptionAr,
			&i.DescriptionEn,
			&i.DurationMinutes,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.Active,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :execrows
UPDATE catalog.services SET
    category_code = $1, name_ar = $2, name_en = $3,
    description_ar = $4, description_en = $5,
    duration_minutes = $6, price_amount = $7, price_currency = $8,
    active = $9, sort_order = $10, version = $11, updated_at = $12
WHERE id = $13 AND version = $14
`

type UpdateServiceParams struct {
	CategoryCode    string
	NameAr          string
	NameEn          string
	DescriptionAr   string
	DescriptionEn   string
	DurationMinutes int16
	PriceAmount     int64
	PriceCurrency   string
	Active          bool
	SortOrder       int16
	Version         int32
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateService,
		arg.CategoryCode,
		arg.NameAr,
		arg.NameEn,
		arg.DescriptionAr,
		arg.DescriptionEn,
		arg.DurationMinutes,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Active,
		arg.SortOrder,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
