// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingSubscription struct {
	BusinessID       uuid.UUID
	PlanCode         string
	Status           string
	CurrentPeriodEnd time.Time
	CreatedAt        time.Time
}

type BookingAppointment struct {
	ID               uuid.UUID
	BusinessID       uuid.UUID
	BranchID         uuid.UUID
	StaffID          uuid.UUID
	CustomerID       pgtype.UUID
	Status           string
	Source           string
	Assignment       string
	StartsAt         time.Time
	EndsAt           time.Time
	During           pgtype.Range[pgtype.Timestamptz]
	PriceAmount      int64
	PriceCurrency    string
	CustomerNote     string
	PendingUntil     *time.Time
	CancelledBy      *string
	CancelReason     string
	CancelledAt      *time.Time
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CancellableUntil time.Time
	CustomerName     string
}

type BookingAppointmentItem struct {
	AppointmentID   uuid.UUID
	Position        int16
	ServiceID       uuid.UUID
	NameAr          string
	NameEn          string
	DurationMinutes int16
	PriceAmount     int64
	PriceCurrency   string
}

type BookingIdempotencyKey struct {
	RequesterID   uuid.UUID
	Key           uuid.UUID
	RequestHash   []byte
	AppointmentID pgtype.UUID
	CreatedAt     time.Time
}

type BusinessBranch struct {
	ID                   uuid.UUID
	BusinessID           uuid.UUID
	NameAr               string
	NameEn               string
	CityCode             string
	District             string
	Address              string
	Latitude             float64
	Longitude            float64
	Phone                *string
	Timezone             string
	Status               string
	MinLeadMinutes       int32
	HorizonDays          int16
	SlotIntervalMinutes  int16
	BufferMinutes        int16
	CancellationMinutes  int32
	AutoConfirm          bool
	PendingExpiryMinutes int16
	MaxActiveBookings    int16
	Version              int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type BusinessBusiness struct {
	ID              uuid.UUID
	OwnerUserID     uuid.UUID
	DisplayNameAr   string
	DisplayNameEn   string
	LegalName       string
	CrNumber        string
	Status          string
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	SubmittedAt     *time.Time
	ReviewedAt      *time.Time
	ReviewedBy      pgtype.UUID
	RejectionReason string
}

type BusinessInvitation struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	Phone       string
	DisplayName string
	Role        string
	BranchIds   []uuid.UUID
	TokenHash   []byte
	Status      string
	InvitedBy   uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
	AcceptedAt  *time.Time
	AcceptedBy  pgtype.UUID
}

type BusinessStaffBranch struct {
	StaffID    uuid.UUID
	BranchID   uuid.UUID
	BusinessID uuid.UUID
}

type BusinessStaffMember struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	UserID      pgtype.UUID
	Role        string
	Active      bool
	CreatedAt   time.Time
	DisplayName string
}

type BusinessVerificationDocument struct {
	ObjectID    uuid.UUID
	BusinessID  uuid.UUID
	Kind        string
	ContentType string
	SizeBytes   int64
	UploadedBy  uuid.UUID
	UploadedAt  time.Time
}

type CatalogService struct {
	ID              uuid.UUID
	BusinessID      uuid.UUID
	BranchID        uuid.UUID
	CategoryCode    string
	NameAr          string
	NameEn          string
	DescriptionAr   string
	DescriptionEn   string
	DurationMinutes int16
	PriceAmount     int64
	PriceCurrency   string
	Active          bool
	SortOrder       int16
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type CatalogServiceOffering struct {
	BusinessID      uuid.UUID
	ServiceID       uuid.UUID
	StaffID         uuid.UUID
	PriceAmount     pgtype.Int8
	PriceCurrency   pgtype.Text
	DurationMinutes pgtype.Int2
}

type DiscoveryBranchHour struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Open       pgtype.Multirange[pgtype.Range[pgtype.Int4]]
	UpdatedAt  time.Time
	Intervals  []byte
}

type DiscoveryBranchListing struct {
	BranchID   uuid.UUID
	BusinessID uuid.UUID
	Version    int32
	Listed     bool
	NameAr     string
	NameEn     string
	CityCode   string
	District   string
	Address    string
	Latitude   float64
	Longitude  float64
	Phone      string
	Timezone   string
	UpdatedAt  time.Time
	Location   interface{}
	SearchText string
}

type DiscoveryBranchService struct {
	ServiceID       uuid.UUID
	BranchID        uuid.UUID
	BusinessID      uuid.UUID
	Version         int32
	Offered         bool
	CategoryCode    string
	PriceFrom       int64
	UpdatedAt       time.Time
	NameAr          string
	NameEn          string
	DurationMinutes int32
	SortOrder       int32
}

type IamOtpChallenge struct {
	ID         uuid.UUID
	Phone      string
	CodeHash   []byte
	Attempts   int16
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt *time.Time
}

type IamOtpPhoneGuard struct {
	Phone       string
	Failures    int16
	WindowStart time.Time
	LockedUntil time.Time
}

type IamRefreshToken struct {
	TokenHash []byte
	SessionID uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type IamSession struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	CreatedAt       time.Time
	LastRefreshedAt time.Time
	RevokedAt       *time.Time
	RevokeReason    *string
}

type IamUser struct {
	ID           uuid.UUID
	Phone        string
	Name         *string
	Locale       string
	Status       string
	PlatformRole string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MediaObject struct {
	ID          uuid.UUID
	Purpose     string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

type SchedulingBarberHour struct {
	BusinessID      uuid.UUID
	BranchID        uuid.UUID
	StaffID         uuid.UUID
	Weekday         int16
	StartMinute     int16
	DurationMinutes int16
}

type SchedulingBarberSchedule struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
	StaffID    uuid.UUID
	Version    int32
	UpdatedAt  time.Time
}

type SchedulingBranchCalendar struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
	Version    int32
	UpdatedAt  time.Time
}

type SchedulingOpeningHour struct {
	BusinessID      uuid.UUID
	BranchID        uuid.UUID
	Weekday         int16
	StartMinute     int16
	DurationMinutes int16
}

type SchedulingOverrideHour struct {
	BusinessID      uuid.UUID
	BranchID        uuid.UUID
	StaffID         uuid.UUID
	OnDate          time.Time
	StartMinute     int16
	DurationMinutes int16
}

type SchedulingScheduleOverride struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
	StaffID    uuid.UUID
	OnDate     time.Time
}

type SchedulingTimeOff struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	StaffID    uuid.UUID
	StartsAt   time.Time
	EndsAt     time.Time
	Reason     string
	CreatedAt  time.Time
}
