// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const calendarByBranch = `-- name: CalendarByBranch :one

SELECT business_id, branch_id, version, updated_at FROM scheduling.branch_calendars WHERE business_id = $1 AND branch_id = $2
`

type CalendarByBranchParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
}

// scheduling's queries. Only the scheduling schema is touched here, and
// every query is scoped by business and branch.
func (q *Queries) CalendarByBranch(ctx context.Context, arg CalendarByBranchParams) (SchedulingBranchCalendar, error) {
	row := q.db.QueryRow(ctx, calendarByBranch, arg.BusinessID, arg.BranchID)
	var i SchedulingBranchCalendar
	err := row.Scan(
		&i.BusinessID,
		&i.BranchID,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const calendarForUpdate = `-- name: CalendarForUpdate :one
SELECT business_id, branch_id, version, updated_at FROM scheduling.branch_calendars WHERE business_id = $1 AND branch_id = $2 FOR UPDATE
`

type CalendarForUpdateParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
}

func (q *Queries) CalendarForUpdate(ctx context.Context, arg CalendarForUpdateParams) (SchedulingBranchCalendar, error) {
	row := q.db.QueryRow(ctx, calendarForUpdate, arg.BusinessID, arg.BranchID)
	var i SchedulingBranchCalendar
	err := row.Scan(
		&i.BusinessID,
		&i.BranchID,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOpeningHours = `-- name: DeleteOpeningHours :exec
DELETE FROM scheduling.opening_hours WHERE business_id = $1 AND branch_id = $2
`

type DeleteOpeningHoursParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
}

func (q *Queries) DeleteOpeningHours(ctx context.Context, arg DeleteOpeningHoursParams) error {
	_, err := q.db.Exec(ctx, deleteOpeningHours, arg.BusinessID, arg.BranchID)
	return err
}

const insertCalendar = `-- name: InsertCalendar :exec
INSERT INTO scheduling.branch_calendars (business_id, branch_id, version, updated_at) VALUES ($1, $2, $3, $4)
`

type InsertCalendarParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
	Version    int32
	UpdatedAt  time.Time
}

func (q *Queries) InsertCalendar(ctx context.Context, arg InsertCalendarParams) error {
	_, err := q.db.Exec(ctx, insertCalendar,
		arg.BusinessID,
		arg.BranchID,
		arg.Version,
		arg.UpdatedAt,
	)
	return err
}

const insertOpeningHour = `-- name: InsertOpeningHour :exec
INSERT INTO scheduling.opening_hours (business_id, branch_id, weekday, start_minute, duration_minutes) VALUES ($1, $2, $3, $4, $5)
`

type InsertOpeningHourParams struct {
	BusinessID      uuid.UUID
	BranchID        uuid.UUID
	Weekday         int16
	StartMinute     int16
	DurationMinutes int16
}

func (q *Queries) InsertOpeningHour(ctx context.Context, arg InsertOpeningHourParams) error {
	_, err := q.db.Exec(ctx, insertOpeningHour,
		arg.BusinessID,
		arg.BranchID,
		arg.Weekday,
		arg.StartMinute,
		arg.DurationMinutes,
	)
	return err
}

const openingHours = `-- name: OpeningHours :many
SELECT business_id, branch_id, weekday, start_minute, duration_minutes FROM scheduling.opening_hours WHERE business_id = $1 AND branch_id = $2 ORDER BY weekday, start_minute
`

type OpeningHoursParams struct {
	BusinessID uuid.UUID
	BranchID   uuid.UUID
}

func (q *Queries) OpeningHours(ctx context.Context, arg OpeningHoursParams) ([]SchedulingOpeningHour, error) {
	rows, err := q.db.Query(ctx, openingHours, arg.BusinessID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingOpeningHour{}
	for rows.Next() {
		var i SchedulingOpeningHour
		if err := rows.Scan(
			&i.BusinessID,
			&i.BranchID,
			&i.Weekday,
			&i.StartMinute,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendar = `-- name: UpdateCalendar :execrows
UPDATE scheduling.branch_calendars SET version = $1, updated_at = $2
WHERE business_id = $3 AND branch_id = $4 AND version = $5
`

type UpdateCalendarParams struct {
	Version         int32
	UpdatedAt       time.Time
	BusinessID      uuid.UUID
	BranchID        uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCalendar,
		arg.Version,
		arg.UpdatedAt,
		arg.BusinessID,
		arg.BranchID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
