// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSubscriptionIfAbsent = `-- name: InsertSubscriptionIfAbsent :execrows

INSERT INTO billing.subscriptions (business_id, plan_code, status, current_period_end, created_at)
VALUES ($1, $2, 'trialing', $3, $4)
ON CONFLICT (business_id) DO NOTHING
`

type InsertSubscriptionIfAbsentParams struct {
	BusinessID       uuid.UUID
	PlanCode         string
	CurrentPeriodEnd time.Time
	CreatedAt        time.Time
}

// billing's queries. Only the billing schema is touched here.
func (q *Queries) InsertSubscriptionIfAbsent(ctx context.Context, arg InsertSubscriptionIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSubscriptionIfAbsent,
		arg.BusinessID,
		arg.PlanCode,
		arg.CurrentPeriodEnd,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subscriptionByBusiness = `-- name: SubscriptionByBusiness :one
SELECT business_id, plan_code, status, current_period_end, created_at FROM billing.subscriptions WHERE business_id = $1
`

func (q *Queries) SubscriptionByBusiness(ctx context.Context, businessID uuid.UUID) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, subscriptionByBusiness, businessID)
	var i BillingSubscription
	err := row.Scan(
		&i.BusinessID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}
